/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */
import * as runtime from "@prisma/client/runtime/client";
import {} from "./class.js";
/**
 * Prisma Errors
 */
export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError;
export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError;
export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError;
export const PrismaClientInitializationError = runtime.PrismaClientInitializationError;
export const PrismaClientValidationError = runtime.PrismaClientValidationError;
/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag;
export const empty = runtime.empty;
export const join = runtime.join;
export const raw = runtime.raw;
export const Sql = runtime.Sql;
/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal;
export const getExtensionContext = runtime.Extensions.getExtensionContext;
/**
 * Prisma Client JS version: 7.6.0
 * Query Engine version: 75cbdc1eb7150937890ad5465d861175c6624711
 */
export const prismaVersion = {
    client: "7.6.0",
    engine: "75cbdc1eb7150937890ad5465d861175c6624711"
};
export const NullTypes = {
    DbNull: runtime.NullTypes.DbNull,
    JsonNull: runtime.NullTypes.JsonNull,
    AnyNull: runtime.NullTypes.AnyNull,
};
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull;
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull;
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull;
export const ModelName = {
    User: 'User',
    Teacher: 'Teacher',
    CoachingCenter: 'CoachingCenter',
    Subject: 'Subject',
    CoachingStaff: 'CoachingStaff',
    DemoClass: 'DemoClass',
    Batch: 'Batch',
    Enrollment: 'Enrollment'
};
/**
 * Enums
 */
export const TransactionIsolationLevel = runtime.makeStrictEnum({
    ReadUncommitted: 'ReadUncommitted',
    ReadCommitted: 'ReadCommitted',
    RepeatableRead: 'RepeatableRead',
    Serializable: 'Serializable'
});
export const UserScalarFieldEnum = {
    id: 'id',
    name: 'name',
    email: 'email',
    mobile: 'mobile',
    password: 'password',
    address: 'address',
    avatar: 'avatar',
    coverImage: 'coverImage',
    bio: 'bio',
    facebook: 'facebook',
    linkedIn: 'linkedIn',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt'
};
export const TeacherScalarFieldEnum = {
    id: 'id',
    userId: 'userId',
    education: 'education',
    certificate: 'certificate',
    experience: 'experience',
    availableDay: 'availableDay',
    availableTime: 'availableTime',
    rating: 'rating',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt'
};
export const CoachingCenterScalarFieldEnum = {
    id: 'id',
    CcName: 'CcName',
    email: 'email',
    address: 'address',
    mobile: 'mobile',
    avatar: 'avatar',
    coverImage: 'coverImage',
    website: 'website',
    officeTime: 'officeTime',
    bio: 'bio',
    facebook: 'facebook',
    linkedIn: 'linkedIn',
    userId: 'userId',
    status: 'status',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt'
};
export const SubjectScalarFieldEnum = {
    id: 'id',
    name: 'name',
    className: 'className',
    userId: 'userId',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt'
};
export const CoachingStaffScalarFieldEnum = {
    id: 'id',
    staffId: 'staffId',
    coachingId: 'coachingId',
    role: 'role',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt'
};
export const DemoClassScalarFieldEnum = {
    id: 'id',
    title: 'title',
    videoURL: 'videoURL',
    subjectId: 'subjectId',
    batchId: 'batchId',
    userId: 'userId',
    status: 'status',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt'
};
export const BatchScalarFieldEnum = {
    id: 'id',
    name: 'name',
    coverImage: 'coverImage',
    start_date: 'start_date',
    end_date: 'end_date',
    capacity: 'capacity',
    price: 'price',
    recurringRule: 'recurringRule',
    coachingId: 'coachingId',
    bio: 'bio',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt'
};
export const EnrollmentScalarFieldEnum = {
    id: 'id',
    studentId: 'studentId',
    batchId: 'batchId',
    status: 'status',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt'
};
export const SortOrder = {
    asc: 'asc',
    desc: 'desc'
};
export const QueryMode = {
    default: 'default',
    insensitive: 'insensitive'
};
export const NullsOrder = {
    first: 'first',
    last: 'last'
};
export const defineExtension = runtime.Extensions.defineExtension;
//# sourceMappingURL=prismaNamespace.js.map