
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Teacher: 'Teacher',
  CoachingCenter: 'CoachingCenter',
  Subject: 'Subject',
  CoachingStaff: 'CoachingStaff',
  DemoClass: 'DemoClass',
  Batch: 'Batch',
  Enrollment: 'Enrollment'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  mobile: 'mobile',
  password: 'password',
  address: 'address',
  avatar: 'avatar',
  coverImage: 'coverImage',
  bio: 'bio',
  facebook: 'facebook',
  linkedIn: 'linkedIn',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const TeacherScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  education: 'education',
  certificate: 'certificate',
  experience: 'experience',
  availableDay: 'availableDay',
  availableTime: 'availableTime',
  rating: 'rating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TeacherScalarFieldEnum = (typeof TeacherScalarFieldEnum)[keyof typeof TeacherScalarFieldEnum]


export const CoachingCenterScalarFieldEnum = {
  id: 'id',
  CcName: 'CcName',
  email: 'email',
  address: 'address',
  mobile: 'mobile',
  avatar: 'avatar',
  coverImage: 'coverImage',
  website: 'website',
  officeTime: 'officeTime',
  bio: 'bio',
  facebook: 'facebook',
  linkedIn: 'linkedIn',
  userId: 'userId',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CoachingCenterScalarFieldEnum = (typeof CoachingCenterScalarFieldEnum)[keyof typeof CoachingCenterScalarFieldEnum]


export const SubjectScalarFieldEnum = {
  id: 'id',
  name: 'name',
  className: 'className',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SubjectScalarFieldEnum = (typeof SubjectScalarFieldEnum)[keyof typeof SubjectScalarFieldEnum]


export const CoachingStaffScalarFieldEnum = {
  id: 'id',
  staffId: 'staffId',
  coachingId: 'coachingId',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CoachingStaffScalarFieldEnum = (typeof CoachingStaffScalarFieldEnum)[keyof typeof CoachingStaffScalarFieldEnum]


export const DemoClassScalarFieldEnum = {
  id: 'id',
  title: 'title',
  videoURL: 'videoURL',
  subjectId: 'subjectId',
  batchId: 'batchId',
  userId: 'userId',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DemoClassScalarFieldEnum = (typeof DemoClassScalarFieldEnum)[keyof typeof DemoClassScalarFieldEnum]


export const BatchScalarFieldEnum = {
  id: 'id',
  name: 'name',
  coverImage: 'coverImage',
  start_date: 'start_date',
  end_date: 'end_date',
  capacity: 'capacity',
  price: 'price',
  recurringRule: 'recurringRule',
  coachingId: 'coachingId',
  bio: 'bio',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BatchScalarFieldEnum = (typeof BatchScalarFieldEnum)[keyof typeof BatchScalarFieldEnum]


export const EnrollmentScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  batchId: 'batchId',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type EnrollmentScalarFieldEnum = (typeof EnrollmentScalarFieldEnum)[keyof typeof EnrollmentScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

