
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Batch` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Batch
 * 
 */
export type BatchModel = runtime.Types.Result.DefaultSelection<Prisma.$BatchPayload>

export type AggregateBatch = {
  _count: BatchCountAggregateOutputType | null
  _avg: BatchAvgAggregateOutputType | null
  _sum: BatchSumAggregateOutputType | null
  _min: BatchMinAggregateOutputType | null
  _max: BatchMaxAggregateOutputType | null
}

export type BatchAvgAggregateOutputType = {
  capacity: number | null
  price: number | null
}

export type BatchSumAggregateOutputType = {
  capacity: number | null
  price: number | null
}

export type BatchMinAggregateOutputType = {
  id: string | null
  name: string | null
  coverImage: string | null
  start_date: string | null
  end_date: string | null
  capacity: number | null
  price: number | null
  coachingId: string | null
  bio: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BatchMaxAggregateOutputType = {
  id: string | null
  name: string | null
  coverImage: string | null
  start_date: string | null
  end_date: string | null
  capacity: number | null
  price: number | null
  coachingId: string | null
  bio: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BatchCountAggregateOutputType = {
  id: number
  name: number
  coverImage: number
  start_date: number
  end_date: number
  capacity: number
  price: number
  recurringRule: number
  coachingId: number
  bio: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type BatchAvgAggregateInputType = {
  capacity?: true
  price?: true
}

export type BatchSumAggregateInputType = {
  capacity?: true
  price?: true
}

export type BatchMinAggregateInputType = {
  id?: true
  name?: true
  coverImage?: true
  start_date?: true
  end_date?: true
  capacity?: true
  price?: true
  coachingId?: true
  bio?: true
  createdAt?: true
  updatedAt?: true
}

export type BatchMaxAggregateInputType = {
  id?: true
  name?: true
  coverImage?: true
  start_date?: true
  end_date?: true
  capacity?: true
  price?: true
  coachingId?: true
  bio?: true
  createdAt?: true
  updatedAt?: true
}

export type BatchCountAggregateInputType = {
  id?: true
  name?: true
  coverImage?: true
  start_date?: true
  end_date?: true
  capacity?: true
  price?: true
  recurringRule?: true
  coachingId?: true
  bio?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type BatchAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Batch to aggregate.
   */
  where?: Prisma.BatchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Batches to fetch.
   */
  orderBy?: Prisma.BatchOrderByWithRelationInput | Prisma.BatchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BatchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Batches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Batches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Batches
  **/
  _count?: true | BatchCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BatchAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BatchSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BatchMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BatchMaxAggregateInputType
}

export type GetBatchAggregateType<T extends BatchAggregateArgs> = {
      [P in keyof T & keyof AggregateBatch]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBatch[P]>
    : Prisma.GetScalarType<T[P], AggregateBatch[P]>
}




export type BatchGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BatchWhereInput
  orderBy?: Prisma.BatchOrderByWithAggregationInput | Prisma.BatchOrderByWithAggregationInput[]
  by: Prisma.BatchScalarFieldEnum[] | Prisma.BatchScalarFieldEnum
  having?: Prisma.BatchScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BatchCountAggregateInputType | true
  _avg?: BatchAvgAggregateInputType
  _sum?: BatchSumAggregateInputType
  _min?: BatchMinAggregateInputType
  _max?: BatchMaxAggregateInputType
}

export type BatchGroupByOutputType = {
  id: string
  name: string
  coverImage: string | null
  start_date: string
  end_date: string
  capacity: number
  price: number
  recurringRule: string[]
  coachingId: string
  bio: string | null
  createdAt: Date
  updatedAt: Date
  _count: BatchCountAggregateOutputType | null
  _avg: BatchAvgAggregateOutputType | null
  _sum: BatchSumAggregateOutputType | null
  _min: BatchMinAggregateOutputType | null
  _max: BatchMaxAggregateOutputType | null
}

export type GetBatchGroupByPayload<T extends BatchGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BatchGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BatchGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BatchGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BatchGroupByOutputType[P]>
      }
    >
  >



export type BatchWhereInput = {
  AND?: Prisma.BatchWhereInput | Prisma.BatchWhereInput[]
  OR?: Prisma.BatchWhereInput[]
  NOT?: Prisma.BatchWhereInput | Prisma.BatchWhereInput[]
  id?: Prisma.StringFilter<"Batch"> | string
  name?: Prisma.StringFilter<"Batch"> | string
  coverImage?: Prisma.StringNullableFilter<"Batch"> | string | null
  start_date?: Prisma.StringFilter<"Batch"> | string
  end_date?: Prisma.StringFilter<"Batch"> | string
  capacity?: Prisma.IntFilter<"Batch"> | number
  price?: Prisma.IntFilter<"Batch"> | number
  recurringRule?: Prisma.StringNullableListFilter<"Batch">
  coachingId?: Prisma.StringFilter<"Batch"> | string
  bio?: Prisma.StringNullableFilter<"Batch"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Batch"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Batch"> | Date | string
  subjects?: Prisma.SubjectListRelationFilter
  assignedTeachers?: Prisma.UserListRelationFilter
  coaching?: Prisma.XOR<Prisma.CoachingCenterScalarRelationFilter, Prisma.CoachingCenterWhereInput>
  demoClasses?: Prisma.DemoClassListRelationFilter
  enrollments?: Prisma.EnrollmentListRelationFilter
}

export type BatchOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  coverImage?: Prisma.SortOrderInput | Prisma.SortOrder
  start_date?: Prisma.SortOrder
  end_date?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
  price?: Prisma.SortOrder
  recurringRule?: Prisma.SortOrder
  coachingId?: Prisma.SortOrder
  bio?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  subjects?: Prisma.SubjectOrderByRelationAggregateInput
  assignedTeachers?: Prisma.UserOrderByRelationAggregateInput
  coaching?: Prisma.CoachingCenterOrderByWithRelationInput
  demoClasses?: Prisma.DemoClassOrderByRelationAggregateInput
  enrollments?: Prisma.EnrollmentOrderByRelationAggregateInput
}

export type BatchWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BatchWhereInput | Prisma.BatchWhereInput[]
  OR?: Prisma.BatchWhereInput[]
  NOT?: Prisma.BatchWhereInput | Prisma.BatchWhereInput[]
  name?: Prisma.StringFilter<"Batch"> | string
  coverImage?: Prisma.StringNullableFilter<"Batch"> | string | null
  start_date?: Prisma.StringFilter<"Batch"> | string
  end_date?: Prisma.StringFilter<"Batch"> | string
  capacity?: Prisma.IntFilter<"Batch"> | number
  price?: Prisma.IntFilter<"Batch"> | number
  recurringRule?: Prisma.StringNullableListFilter<"Batch">
  coachingId?: Prisma.StringFilter<"Batch"> | string
  bio?: Prisma.StringNullableFilter<"Batch"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Batch"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Batch"> | Date | string
  subjects?: Prisma.SubjectListRelationFilter
  assignedTeachers?: Prisma.UserListRelationFilter
  coaching?: Prisma.XOR<Prisma.CoachingCenterScalarRelationFilter, Prisma.CoachingCenterWhereInput>
  demoClasses?: Prisma.DemoClassListRelationFilter
  enrollments?: Prisma.EnrollmentListRelationFilter
}, "id">

export type BatchOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  coverImage?: Prisma.SortOrderInput | Prisma.SortOrder
  start_date?: Prisma.SortOrder
  end_date?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
  price?: Prisma.SortOrder
  recurringRule?: Prisma.SortOrder
  coachingId?: Prisma.SortOrder
  bio?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.BatchCountOrderByAggregateInput
  _avg?: Prisma.BatchAvgOrderByAggregateInput
  _max?: Prisma.BatchMaxOrderByAggregateInput
  _min?: Prisma.BatchMinOrderByAggregateInput
  _sum?: Prisma.BatchSumOrderByAggregateInput
}

export type BatchScalarWhereWithAggregatesInput = {
  AND?: Prisma.BatchScalarWhereWithAggregatesInput | Prisma.BatchScalarWhereWithAggregatesInput[]
  OR?: Prisma.BatchScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BatchScalarWhereWithAggregatesInput | Prisma.BatchScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Batch"> | string
  name?: Prisma.StringWithAggregatesFilter<"Batch"> | string
  coverImage?: Prisma.StringNullableWithAggregatesFilter<"Batch"> | string | null
  start_date?: Prisma.StringWithAggregatesFilter<"Batch"> | string
  end_date?: Prisma.StringWithAggregatesFilter<"Batch"> | string
  capacity?: Prisma.IntWithAggregatesFilter<"Batch"> | number
  price?: Prisma.IntWithAggregatesFilter<"Batch"> | number
  recurringRule?: Prisma.StringNullableListFilter<"Batch">
  coachingId?: Prisma.StringWithAggregatesFilter<"Batch"> | string
  bio?: Prisma.StringNullableWithAggregatesFilter<"Batch"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Batch"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Batch"> | Date | string
}

export type BatchCreateInput = {
  id?: string
  name: string
  coverImage?: string | null
  start_date: string
  end_date: string
  capacity: number
  price: number
  recurringRule?: Prisma.BatchCreaterecurringRuleInput | string[]
  bio?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  subjects?: Prisma.SubjectCreateNestedManyWithoutBatchesInput
  assignedTeachers?: Prisma.UserCreateNestedManyWithoutBatchesInput
  coaching: Prisma.CoachingCenterCreateNestedOneWithoutBatchesInput
  demoClasses?: Prisma.DemoClassCreateNestedManyWithoutBatchInput
  enrollments?: Prisma.EnrollmentCreateNestedManyWithoutBatchInput
}

export type BatchUncheckedCreateInput = {
  id?: string
  name: string
  coverImage?: string | null
  start_date: string
  end_date: string
  capacity: number
  price: number
  recurringRule?: Prisma.BatchCreaterecurringRuleInput | string[]
  coachingId: string
  bio?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  subjects?: Prisma.SubjectUncheckedCreateNestedManyWithoutBatchesInput
  assignedTeachers?: Prisma.UserUncheckedCreateNestedManyWithoutBatchesInput
  demoClasses?: Prisma.DemoClassUncheckedCreateNestedManyWithoutBatchInput
  enrollments?: Prisma.EnrollmentUncheckedCreateNestedManyWithoutBatchInput
}

export type BatchUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_date?: Prisma.StringFieldUpdateOperationsInput | string
  end_date?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  recurringRule?: Prisma.BatchUpdaterecurringRuleInput | string[]
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subjects?: Prisma.SubjectUpdateManyWithoutBatchesNestedInput
  assignedTeachers?: Prisma.UserUpdateManyWithoutBatchesNestedInput
  coaching?: Prisma.CoachingCenterUpdateOneRequiredWithoutBatchesNestedInput
  demoClasses?: Prisma.DemoClassUpdateManyWithoutBatchNestedInput
  enrollments?: Prisma.EnrollmentUpdateManyWithoutBatchNestedInput
}

export type BatchUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_date?: Prisma.StringFieldUpdateOperationsInput | string
  end_date?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  recurringRule?: Prisma.BatchUpdaterecurringRuleInput | string[]
  coachingId?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subjects?: Prisma.SubjectUncheckedUpdateManyWithoutBatchesNestedInput
  assignedTeachers?: Prisma.UserUncheckedUpdateManyWithoutBatchesNestedInput
  demoClasses?: Prisma.DemoClassUncheckedUpdateManyWithoutBatchNestedInput
  enrollments?: Prisma.EnrollmentUncheckedUpdateManyWithoutBatchNestedInput
}

export type BatchCreateManyInput = {
  id?: string
  name: string
  coverImage?: string | null
  start_date: string
  end_date: string
  capacity: number
  price: number
  recurringRule?: Prisma.BatchCreaterecurringRuleInput | string[]
  coachingId: string
  bio?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BatchUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_date?: Prisma.StringFieldUpdateOperationsInput | string
  end_date?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  recurringRule?: Prisma.BatchUpdaterecurringRuleInput | string[]
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BatchUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_date?: Prisma.StringFieldUpdateOperationsInput | string
  end_date?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  recurringRule?: Prisma.BatchUpdaterecurringRuleInput | string[]
  coachingId?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BatchListRelationFilter = {
  every?: Prisma.BatchWhereInput
  some?: Prisma.BatchWhereInput
  none?: Prisma.BatchWhereInput
}

export type BatchOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BatchNullableScalarRelationFilter = {
  is?: Prisma.BatchWhereInput | null
  isNot?: Prisma.BatchWhereInput | null
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type BatchCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  coverImage?: Prisma.SortOrder
  start_date?: Prisma.SortOrder
  end_date?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
  price?: Prisma.SortOrder
  recurringRule?: Prisma.SortOrder
  coachingId?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BatchAvgOrderByAggregateInput = {
  capacity?: Prisma.SortOrder
  price?: Prisma.SortOrder
}

export type BatchMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  coverImage?: Prisma.SortOrder
  start_date?: Prisma.SortOrder
  end_date?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
  price?: Prisma.SortOrder
  coachingId?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BatchMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  coverImage?: Prisma.SortOrder
  start_date?: Prisma.SortOrder
  end_date?: Prisma.SortOrder
  capacity?: Prisma.SortOrder
  price?: Prisma.SortOrder
  coachingId?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BatchSumOrderByAggregateInput = {
  capacity?: Prisma.SortOrder
  price?: Prisma.SortOrder
}

export type BatchScalarRelationFilter = {
  is?: Prisma.BatchWhereInput
  isNot?: Prisma.BatchWhereInput
}

export type BatchCreateNestedManyWithoutAssignedTeachersInput = {
  create?: Prisma.XOR<Prisma.BatchCreateWithoutAssignedTeachersInput, Prisma.BatchUncheckedCreateWithoutAssignedTeachersInput> | Prisma.BatchCreateWithoutAssignedTeachersInput[] | Prisma.BatchUncheckedCreateWithoutAssignedTeachersInput[]
  connectOrCreate?: Prisma.BatchCreateOrConnectWithoutAssignedTeachersInput | Prisma.BatchCreateOrConnectWithoutAssignedTeachersInput[]
  connect?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
}

export type BatchUncheckedCreateNestedManyWithoutAssignedTeachersInput = {
  create?: Prisma.XOR<Prisma.BatchCreateWithoutAssignedTeachersInput, Prisma.BatchUncheckedCreateWithoutAssignedTeachersInput> | Prisma.BatchCreateWithoutAssignedTeachersInput[] | Prisma.BatchUncheckedCreateWithoutAssignedTeachersInput[]
  connectOrCreate?: Prisma.BatchCreateOrConnectWithoutAssignedTeachersInput | Prisma.BatchCreateOrConnectWithoutAssignedTeachersInput[]
  connect?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
}

export type BatchUpdateManyWithoutAssignedTeachersNestedInput = {
  create?: Prisma.XOR<Prisma.BatchCreateWithoutAssignedTeachersInput, Prisma.BatchUncheckedCreateWithoutAssignedTeachersInput> | Prisma.BatchCreateWithoutAssignedTeachersInput[] | Prisma.BatchUncheckedCreateWithoutAssignedTeachersInput[]
  connectOrCreate?: Prisma.BatchCreateOrConnectWithoutAssignedTeachersInput | Prisma.BatchCreateOrConnectWithoutAssignedTeachersInput[]
  upsert?: Prisma.BatchUpsertWithWhereUniqueWithoutAssignedTeachersInput | Prisma.BatchUpsertWithWhereUniqueWithoutAssignedTeachersInput[]
  set?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  disconnect?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  delete?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  connect?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  update?: Prisma.BatchUpdateWithWhereUniqueWithoutAssignedTeachersInput | Prisma.BatchUpdateWithWhereUniqueWithoutAssignedTeachersInput[]
  updateMany?: Prisma.BatchUpdateManyWithWhereWithoutAssignedTeachersInput | Prisma.BatchUpdateManyWithWhereWithoutAssignedTeachersInput[]
  deleteMany?: Prisma.BatchScalarWhereInput | Prisma.BatchScalarWhereInput[]
}

export type BatchUncheckedUpdateManyWithoutAssignedTeachersNestedInput = {
  create?: Prisma.XOR<Prisma.BatchCreateWithoutAssignedTeachersInput, Prisma.BatchUncheckedCreateWithoutAssignedTeachersInput> | Prisma.BatchCreateWithoutAssignedTeachersInput[] | Prisma.BatchUncheckedCreateWithoutAssignedTeachersInput[]
  connectOrCreate?: Prisma.BatchCreateOrConnectWithoutAssignedTeachersInput | Prisma.BatchCreateOrConnectWithoutAssignedTeachersInput[]
  upsert?: Prisma.BatchUpsertWithWhereUniqueWithoutAssignedTeachersInput | Prisma.BatchUpsertWithWhereUniqueWithoutAssignedTeachersInput[]
  set?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  disconnect?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  delete?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  connect?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  update?: Prisma.BatchUpdateWithWhereUniqueWithoutAssignedTeachersInput | Prisma.BatchUpdateWithWhereUniqueWithoutAssignedTeachersInput[]
  updateMany?: Prisma.BatchUpdateManyWithWhereWithoutAssignedTeachersInput | Prisma.BatchUpdateManyWithWhereWithoutAssignedTeachersInput[]
  deleteMany?: Prisma.BatchScalarWhereInput | Prisma.BatchScalarWhereInput[]
}

export type BatchCreateNestedManyWithoutCoachingInput = {
  create?: Prisma.XOR<Prisma.BatchCreateWithoutCoachingInput, Prisma.BatchUncheckedCreateWithoutCoachingInput> | Prisma.BatchCreateWithoutCoachingInput[] | Prisma.BatchUncheckedCreateWithoutCoachingInput[]
  connectOrCreate?: Prisma.BatchCreateOrConnectWithoutCoachingInput | Prisma.BatchCreateOrConnectWithoutCoachingInput[]
  createMany?: Prisma.BatchCreateManyCoachingInputEnvelope
  connect?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
}

export type BatchUncheckedCreateNestedManyWithoutCoachingInput = {
  create?: Prisma.XOR<Prisma.BatchCreateWithoutCoachingInput, Prisma.BatchUncheckedCreateWithoutCoachingInput> | Prisma.BatchCreateWithoutCoachingInput[] | Prisma.BatchUncheckedCreateWithoutCoachingInput[]
  connectOrCreate?: Prisma.BatchCreateOrConnectWithoutCoachingInput | Prisma.BatchCreateOrConnectWithoutCoachingInput[]
  createMany?: Prisma.BatchCreateManyCoachingInputEnvelope
  connect?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
}

export type BatchUpdateManyWithoutCoachingNestedInput = {
  create?: Prisma.XOR<Prisma.BatchCreateWithoutCoachingInput, Prisma.BatchUncheckedCreateWithoutCoachingInput> | Prisma.BatchCreateWithoutCoachingInput[] | Prisma.BatchUncheckedCreateWithoutCoachingInput[]
  connectOrCreate?: Prisma.BatchCreateOrConnectWithoutCoachingInput | Prisma.BatchCreateOrConnectWithoutCoachingInput[]
  upsert?: Prisma.BatchUpsertWithWhereUniqueWithoutCoachingInput | Prisma.BatchUpsertWithWhereUniqueWithoutCoachingInput[]
  createMany?: Prisma.BatchCreateManyCoachingInputEnvelope
  set?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  disconnect?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  delete?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  connect?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  update?: Prisma.BatchUpdateWithWhereUniqueWithoutCoachingInput | Prisma.BatchUpdateWithWhereUniqueWithoutCoachingInput[]
  updateMany?: Prisma.BatchUpdateManyWithWhereWithoutCoachingInput | Prisma.BatchUpdateManyWithWhereWithoutCoachingInput[]
  deleteMany?: Prisma.BatchScalarWhereInput | Prisma.BatchScalarWhereInput[]
}

export type BatchUncheckedUpdateManyWithoutCoachingNestedInput = {
  create?: Prisma.XOR<Prisma.BatchCreateWithoutCoachingInput, Prisma.BatchUncheckedCreateWithoutCoachingInput> | Prisma.BatchCreateWithoutCoachingInput[] | Prisma.BatchUncheckedCreateWithoutCoachingInput[]
  connectOrCreate?: Prisma.BatchCreateOrConnectWithoutCoachingInput | Prisma.BatchCreateOrConnectWithoutCoachingInput[]
  upsert?: Prisma.BatchUpsertWithWhereUniqueWithoutCoachingInput | Prisma.BatchUpsertWithWhereUniqueWithoutCoachingInput[]
  createMany?: Prisma.BatchCreateManyCoachingInputEnvelope
  set?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  disconnect?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  delete?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  connect?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  update?: Prisma.BatchUpdateWithWhereUniqueWithoutCoachingInput | Prisma.BatchUpdateWithWhereUniqueWithoutCoachingInput[]
  updateMany?: Prisma.BatchUpdateManyWithWhereWithoutCoachingInput | Prisma.BatchUpdateManyWithWhereWithoutCoachingInput[]
  deleteMany?: Prisma.BatchScalarWhereInput | Prisma.BatchScalarWhereInput[]
}

export type BatchCreateNestedManyWithoutSubjectsInput = {
  create?: Prisma.XOR<Prisma.BatchCreateWithoutSubjectsInput, Prisma.BatchUncheckedCreateWithoutSubjectsInput> | Prisma.BatchCreateWithoutSubjectsInput[] | Prisma.BatchUncheckedCreateWithoutSubjectsInput[]
  connectOrCreate?: Prisma.BatchCreateOrConnectWithoutSubjectsInput | Prisma.BatchCreateOrConnectWithoutSubjectsInput[]
  connect?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
}

export type BatchUncheckedCreateNestedManyWithoutSubjectsInput = {
  create?: Prisma.XOR<Prisma.BatchCreateWithoutSubjectsInput, Prisma.BatchUncheckedCreateWithoutSubjectsInput> | Prisma.BatchCreateWithoutSubjectsInput[] | Prisma.BatchUncheckedCreateWithoutSubjectsInput[]
  connectOrCreate?: Prisma.BatchCreateOrConnectWithoutSubjectsInput | Prisma.BatchCreateOrConnectWithoutSubjectsInput[]
  connect?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
}

export type BatchUpdateManyWithoutSubjectsNestedInput = {
  create?: Prisma.XOR<Prisma.BatchCreateWithoutSubjectsInput, Prisma.BatchUncheckedCreateWithoutSubjectsInput> | Prisma.BatchCreateWithoutSubjectsInput[] | Prisma.BatchUncheckedCreateWithoutSubjectsInput[]
  connectOrCreate?: Prisma.BatchCreateOrConnectWithoutSubjectsInput | Prisma.BatchCreateOrConnectWithoutSubjectsInput[]
  upsert?: Prisma.BatchUpsertWithWhereUniqueWithoutSubjectsInput | Prisma.BatchUpsertWithWhereUniqueWithoutSubjectsInput[]
  set?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  disconnect?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  delete?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  connect?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  update?: Prisma.BatchUpdateWithWhereUniqueWithoutSubjectsInput | Prisma.BatchUpdateWithWhereUniqueWithoutSubjectsInput[]
  updateMany?: Prisma.BatchUpdateManyWithWhereWithoutSubjectsInput | Prisma.BatchUpdateManyWithWhereWithoutSubjectsInput[]
  deleteMany?: Prisma.BatchScalarWhereInput | Prisma.BatchScalarWhereInput[]
}

export type BatchUncheckedUpdateManyWithoutSubjectsNestedInput = {
  create?: Prisma.XOR<Prisma.BatchCreateWithoutSubjectsInput, Prisma.BatchUncheckedCreateWithoutSubjectsInput> | Prisma.BatchCreateWithoutSubjectsInput[] | Prisma.BatchUncheckedCreateWithoutSubjectsInput[]
  connectOrCreate?: Prisma.BatchCreateOrConnectWithoutSubjectsInput | Prisma.BatchCreateOrConnectWithoutSubjectsInput[]
  upsert?: Prisma.BatchUpsertWithWhereUniqueWithoutSubjectsInput | Prisma.BatchUpsertWithWhereUniqueWithoutSubjectsInput[]
  set?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  disconnect?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  delete?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  connect?: Prisma.BatchWhereUniqueInput | Prisma.BatchWhereUniqueInput[]
  update?: Prisma.BatchUpdateWithWhereUniqueWithoutSubjectsInput | Prisma.BatchUpdateWithWhereUniqueWithoutSubjectsInput[]
  updateMany?: Prisma.BatchUpdateManyWithWhereWithoutSubjectsInput | Prisma.BatchUpdateManyWithWhereWithoutSubjectsInput[]
  deleteMany?: Prisma.BatchScalarWhereInput | Prisma.BatchScalarWhereInput[]
}

export type BatchCreateNestedOneWithoutDemoClassesInput = {
  create?: Prisma.XOR<Prisma.BatchCreateWithoutDemoClassesInput, Prisma.BatchUncheckedCreateWithoutDemoClassesInput>
  connectOrCreate?: Prisma.BatchCreateOrConnectWithoutDemoClassesInput
  connect?: Prisma.BatchWhereUniqueInput
}

export type BatchUpdateOneWithoutDemoClassesNestedInput = {
  create?: Prisma.XOR<Prisma.BatchCreateWithoutDemoClassesInput, Prisma.BatchUncheckedCreateWithoutDemoClassesInput>
  connectOrCreate?: Prisma.BatchCreateOrConnectWithoutDemoClassesInput
  upsert?: Prisma.BatchUpsertWithoutDemoClassesInput
  disconnect?: Prisma.BatchWhereInput | boolean
  delete?: Prisma.BatchWhereInput | boolean
  connect?: Prisma.BatchWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BatchUpdateToOneWithWhereWithoutDemoClassesInput, Prisma.BatchUpdateWithoutDemoClassesInput>, Prisma.BatchUncheckedUpdateWithoutDemoClassesInput>
}

export type BatchCreaterecurringRuleInput = {
  set: string[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type BatchUpdaterecurringRuleInput = {
  set?: string[]
  push?: string | string[]
}

export type BatchCreateNestedOneWithoutEnrollmentsInput = {
  create?: Prisma.XOR<Prisma.BatchCreateWithoutEnrollmentsInput, Prisma.BatchUncheckedCreateWithoutEnrollmentsInput>
  connectOrCreate?: Prisma.BatchCreateOrConnectWithoutEnrollmentsInput
  connect?: Prisma.BatchWhereUniqueInput
}

export type BatchUpdateOneRequiredWithoutEnrollmentsNestedInput = {
  create?: Prisma.XOR<Prisma.BatchCreateWithoutEnrollmentsInput, Prisma.BatchUncheckedCreateWithoutEnrollmentsInput>
  connectOrCreate?: Prisma.BatchCreateOrConnectWithoutEnrollmentsInput
  upsert?: Prisma.BatchUpsertWithoutEnrollmentsInput
  connect?: Prisma.BatchWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BatchUpdateToOneWithWhereWithoutEnrollmentsInput, Prisma.BatchUpdateWithoutEnrollmentsInput>, Prisma.BatchUncheckedUpdateWithoutEnrollmentsInput>
}

export type BatchCreateWithoutAssignedTeachersInput = {
  id?: string
  name: string
  coverImage?: string | null
  start_date: string
  end_date: string
  capacity: number
  price: number
  recurringRule?: Prisma.BatchCreaterecurringRuleInput | string[]
  bio?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  subjects?: Prisma.SubjectCreateNestedManyWithoutBatchesInput
  coaching: Prisma.CoachingCenterCreateNestedOneWithoutBatchesInput
  demoClasses?: Prisma.DemoClassCreateNestedManyWithoutBatchInput
  enrollments?: Prisma.EnrollmentCreateNestedManyWithoutBatchInput
}

export type BatchUncheckedCreateWithoutAssignedTeachersInput = {
  id?: string
  name: string
  coverImage?: string | null
  start_date: string
  end_date: string
  capacity: number
  price: number
  recurringRule?: Prisma.BatchCreaterecurringRuleInput | string[]
  coachingId: string
  bio?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  subjects?: Prisma.SubjectUncheckedCreateNestedManyWithoutBatchesInput
  demoClasses?: Prisma.DemoClassUncheckedCreateNestedManyWithoutBatchInput
  enrollments?: Prisma.EnrollmentUncheckedCreateNestedManyWithoutBatchInput
}

export type BatchCreateOrConnectWithoutAssignedTeachersInput = {
  where: Prisma.BatchWhereUniqueInput
  create: Prisma.XOR<Prisma.BatchCreateWithoutAssignedTeachersInput, Prisma.BatchUncheckedCreateWithoutAssignedTeachersInput>
}

export type BatchUpsertWithWhereUniqueWithoutAssignedTeachersInput = {
  where: Prisma.BatchWhereUniqueInput
  update: Prisma.XOR<Prisma.BatchUpdateWithoutAssignedTeachersInput, Prisma.BatchUncheckedUpdateWithoutAssignedTeachersInput>
  create: Prisma.XOR<Prisma.BatchCreateWithoutAssignedTeachersInput, Prisma.BatchUncheckedCreateWithoutAssignedTeachersInput>
}

export type BatchUpdateWithWhereUniqueWithoutAssignedTeachersInput = {
  where: Prisma.BatchWhereUniqueInput
  data: Prisma.XOR<Prisma.BatchUpdateWithoutAssignedTeachersInput, Prisma.BatchUncheckedUpdateWithoutAssignedTeachersInput>
}

export type BatchUpdateManyWithWhereWithoutAssignedTeachersInput = {
  where: Prisma.BatchScalarWhereInput
  data: Prisma.XOR<Prisma.BatchUpdateManyMutationInput, Prisma.BatchUncheckedUpdateManyWithoutAssignedTeachersInput>
}

export type BatchScalarWhereInput = {
  AND?: Prisma.BatchScalarWhereInput | Prisma.BatchScalarWhereInput[]
  OR?: Prisma.BatchScalarWhereInput[]
  NOT?: Prisma.BatchScalarWhereInput | Prisma.BatchScalarWhereInput[]
  id?: Prisma.StringFilter<"Batch"> | string
  name?: Prisma.StringFilter<"Batch"> | string
  coverImage?: Prisma.StringNullableFilter<"Batch"> | string | null
  start_date?: Prisma.StringFilter<"Batch"> | string
  end_date?: Prisma.StringFilter<"Batch"> | string
  capacity?: Prisma.IntFilter<"Batch"> | number
  price?: Prisma.IntFilter<"Batch"> | number
  recurringRule?: Prisma.StringNullableListFilter<"Batch">
  coachingId?: Prisma.StringFilter<"Batch"> | string
  bio?: Prisma.StringNullableFilter<"Batch"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Batch"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Batch"> | Date | string
}

export type BatchCreateWithoutCoachingInput = {
  id?: string
  name: string
  coverImage?: string | null
  start_date: string
  end_date: string
  capacity: number
  price: number
  recurringRule?: Prisma.BatchCreaterecurringRuleInput | string[]
  bio?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  subjects?: Prisma.SubjectCreateNestedManyWithoutBatchesInput
  assignedTeachers?: Prisma.UserCreateNestedManyWithoutBatchesInput
  demoClasses?: Prisma.DemoClassCreateNestedManyWithoutBatchInput
  enrollments?: Prisma.EnrollmentCreateNestedManyWithoutBatchInput
}

export type BatchUncheckedCreateWithoutCoachingInput = {
  id?: string
  name: string
  coverImage?: string | null
  start_date: string
  end_date: string
  capacity: number
  price: number
  recurringRule?: Prisma.BatchCreaterecurringRuleInput | string[]
  bio?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  subjects?: Prisma.SubjectUncheckedCreateNestedManyWithoutBatchesInput
  assignedTeachers?: Prisma.UserUncheckedCreateNestedManyWithoutBatchesInput
  demoClasses?: Prisma.DemoClassUncheckedCreateNestedManyWithoutBatchInput
  enrollments?: Prisma.EnrollmentUncheckedCreateNestedManyWithoutBatchInput
}

export type BatchCreateOrConnectWithoutCoachingInput = {
  where: Prisma.BatchWhereUniqueInput
  create: Prisma.XOR<Prisma.BatchCreateWithoutCoachingInput, Prisma.BatchUncheckedCreateWithoutCoachingInput>
}

export type BatchCreateManyCoachingInputEnvelope = {
  data: Prisma.BatchCreateManyCoachingInput | Prisma.BatchCreateManyCoachingInput[]
  skipDuplicates?: boolean
}

export type BatchUpsertWithWhereUniqueWithoutCoachingInput = {
  where: Prisma.BatchWhereUniqueInput
  update: Prisma.XOR<Prisma.BatchUpdateWithoutCoachingInput, Prisma.BatchUncheckedUpdateWithoutCoachingInput>
  create: Prisma.XOR<Prisma.BatchCreateWithoutCoachingInput, Prisma.BatchUncheckedCreateWithoutCoachingInput>
}

export type BatchUpdateWithWhereUniqueWithoutCoachingInput = {
  where: Prisma.BatchWhereUniqueInput
  data: Prisma.XOR<Prisma.BatchUpdateWithoutCoachingInput, Prisma.BatchUncheckedUpdateWithoutCoachingInput>
}

export type BatchUpdateManyWithWhereWithoutCoachingInput = {
  where: Prisma.BatchScalarWhereInput
  data: Prisma.XOR<Prisma.BatchUpdateManyMutationInput, Prisma.BatchUncheckedUpdateManyWithoutCoachingInput>
}

export type BatchCreateWithoutSubjectsInput = {
  id?: string
  name: string
  coverImage?: string | null
  start_date: string
  end_date: string
  capacity: number
  price: number
  recurringRule?: Prisma.BatchCreaterecurringRuleInput | string[]
  bio?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  assignedTeachers?: Prisma.UserCreateNestedManyWithoutBatchesInput
  coaching: Prisma.CoachingCenterCreateNestedOneWithoutBatchesInput
  demoClasses?: Prisma.DemoClassCreateNestedManyWithoutBatchInput
  enrollments?: Prisma.EnrollmentCreateNestedManyWithoutBatchInput
}

export type BatchUncheckedCreateWithoutSubjectsInput = {
  id?: string
  name: string
  coverImage?: string | null
  start_date: string
  end_date: string
  capacity: number
  price: number
  recurringRule?: Prisma.BatchCreaterecurringRuleInput | string[]
  coachingId: string
  bio?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  assignedTeachers?: Prisma.UserUncheckedCreateNestedManyWithoutBatchesInput
  demoClasses?: Prisma.DemoClassUncheckedCreateNestedManyWithoutBatchInput
  enrollments?: Prisma.EnrollmentUncheckedCreateNestedManyWithoutBatchInput
}

export type BatchCreateOrConnectWithoutSubjectsInput = {
  where: Prisma.BatchWhereUniqueInput
  create: Prisma.XOR<Prisma.BatchCreateWithoutSubjectsInput, Prisma.BatchUncheckedCreateWithoutSubjectsInput>
}

export type BatchUpsertWithWhereUniqueWithoutSubjectsInput = {
  where: Prisma.BatchWhereUniqueInput
  update: Prisma.XOR<Prisma.BatchUpdateWithoutSubjectsInput, Prisma.BatchUncheckedUpdateWithoutSubjectsInput>
  create: Prisma.XOR<Prisma.BatchCreateWithoutSubjectsInput, Prisma.BatchUncheckedCreateWithoutSubjectsInput>
}

export type BatchUpdateWithWhereUniqueWithoutSubjectsInput = {
  where: Prisma.BatchWhereUniqueInput
  data: Prisma.XOR<Prisma.BatchUpdateWithoutSubjectsInput, Prisma.BatchUncheckedUpdateWithoutSubjectsInput>
}

export type BatchUpdateManyWithWhereWithoutSubjectsInput = {
  where: Prisma.BatchScalarWhereInput
  data: Prisma.XOR<Prisma.BatchUpdateManyMutationInput, Prisma.BatchUncheckedUpdateManyWithoutSubjectsInput>
}

export type BatchCreateWithoutDemoClassesInput = {
  id?: string
  name: string
  coverImage?: string | null
  start_date: string
  end_date: string
  capacity: number
  price: number
  recurringRule?: Prisma.BatchCreaterecurringRuleInput | string[]
  bio?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  subjects?: Prisma.SubjectCreateNestedManyWithoutBatchesInput
  assignedTeachers?: Prisma.UserCreateNestedManyWithoutBatchesInput
  coaching: Prisma.CoachingCenterCreateNestedOneWithoutBatchesInput
  enrollments?: Prisma.EnrollmentCreateNestedManyWithoutBatchInput
}

export type BatchUncheckedCreateWithoutDemoClassesInput = {
  id?: string
  name: string
  coverImage?: string | null
  start_date: string
  end_date: string
  capacity: number
  price: number
  recurringRule?: Prisma.BatchCreaterecurringRuleInput | string[]
  coachingId: string
  bio?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  subjects?: Prisma.SubjectUncheckedCreateNestedManyWithoutBatchesInput
  assignedTeachers?: Prisma.UserUncheckedCreateNestedManyWithoutBatchesInput
  enrollments?: Prisma.EnrollmentUncheckedCreateNestedManyWithoutBatchInput
}

export type BatchCreateOrConnectWithoutDemoClassesInput = {
  where: Prisma.BatchWhereUniqueInput
  create: Prisma.XOR<Prisma.BatchCreateWithoutDemoClassesInput, Prisma.BatchUncheckedCreateWithoutDemoClassesInput>
}

export type BatchUpsertWithoutDemoClassesInput = {
  update: Prisma.XOR<Prisma.BatchUpdateWithoutDemoClassesInput, Prisma.BatchUncheckedUpdateWithoutDemoClassesInput>
  create: Prisma.XOR<Prisma.BatchCreateWithoutDemoClassesInput, Prisma.BatchUncheckedCreateWithoutDemoClassesInput>
  where?: Prisma.BatchWhereInput
}

export type BatchUpdateToOneWithWhereWithoutDemoClassesInput = {
  where?: Prisma.BatchWhereInput
  data: Prisma.XOR<Prisma.BatchUpdateWithoutDemoClassesInput, Prisma.BatchUncheckedUpdateWithoutDemoClassesInput>
}

export type BatchUpdateWithoutDemoClassesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_date?: Prisma.StringFieldUpdateOperationsInput | string
  end_date?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  recurringRule?: Prisma.BatchUpdaterecurringRuleInput | string[]
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subjects?: Prisma.SubjectUpdateManyWithoutBatchesNestedInput
  assignedTeachers?: Prisma.UserUpdateManyWithoutBatchesNestedInput
  coaching?: Prisma.CoachingCenterUpdateOneRequiredWithoutBatchesNestedInput
  enrollments?: Prisma.EnrollmentUpdateManyWithoutBatchNestedInput
}

export type BatchUncheckedUpdateWithoutDemoClassesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_date?: Prisma.StringFieldUpdateOperationsInput | string
  end_date?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  recurringRule?: Prisma.BatchUpdaterecurringRuleInput | string[]
  coachingId?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subjects?: Prisma.SubjectUncheckedUpdateManyWithoutBatchesNestedInput
  assignedTeachers?: Prisma.UserUncheckedUpdateManyWithoutBatchesNestedInput
  enrollments?: Prisma.EnrollmentUncheckedUpdateManyWithoutBatchNestedInput
}

export type BatchCreateWithoutEnrollmentsInput = {
  id?: string
  name: string
  coverImage?: string | null
  start_date: string
  end_date: string
  capacity: number
  price: number
  recurringRule?: Prisma.BatchCreaterecurringRuleInput | string[]
  bio?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  subjects?: Prisma.SubjectCreateNestedManyWithoutBatchesInput
  assignedTeachers?: Prisma.UserCreateNestedManyWithoutBatchesInput
  coaching: Prisma.CoachingCenterCreateNestedOneWithoutBatchesInput
  demoClasses?: Prisma.DemoClassCreateNestedManyWithoutBatchInput
}

export type BatchUncheckedCreateWithoutEnrollmentsInput = {
  id?: string
  name: string
  coverImage?: string | null
  start_date: string
  end_date: string
  capacity: number
  price: number
  recurringRule?: Prisma.BatchCreaterecurringRuleInput | string[]
  coachingId: string
  bio?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  subjects?: Prisma.SubjectUncheckedCreateNestedManyWithoutBatchesInput
  assignedTeachers?: Prisma.UserUncheckedCreateNestedManyWithoutBatchesInput
  demoClasses?: Prisma.DemoClassUncheckedCreateNestedManyWithoutBatchInput
}

export type BatchCreateOrConnectWithoutEnrollmentsInput = {
  where: Prisma.BatchWhereUniqueInput
  create: Prisma.XOR<Prisma.BatchCreateWithoutEnrollmentsInput, Prisma.BatchUncheckedCreateWithoutEnrollmentsInput>
}

export type BatchUpsertWithoutEnrollmentsInput = {
  update: Prisma.XOR<Prisma.BatchUpdateWithoutEnrollmentsInput, Prisma.BatchUncheckedUpdateWithoutEnrollmentsInput>
  create: Prisma.XOR<Prisma.BatchCreateWithoutEnrollmentsInput, Prisma.BatchUncheckedCreateWithoutEnrollmentsInput>
  where?: Prisma.BatchWhereInput
}

export type BatchUpdateToOneWithWhereWithoutEnrollmentsInput = {
  where?: Prisma.BatchWhereInput
  data: Prisma.XOR<Prisma.BatchUpdateWithoutEnrollmentsInput, Prisma.BatchUncheckedUpdateWithoutEnrollmentsInput>
}

export type BatchUpdateWithoutEnrollmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_date?: Prisma.StringFieldUpdateOperationsInput | string
  end_date?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  recurringRule?: Prisma.BatchUpdaterecurringRuleInput | string[]
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subjects?: Prisma.SubjectUpdateManyWithoutBatchesNestedInput
  assignedTeachers?: Prisma.UserUpdateManyWithoutBatchesNestedInput
  coaching?: Prisma.CoachingCenterUpdateOneRequiredWithoutBatchesNestedInput
  demoClasses?: Prisma.DemoClassUpdateManyWithoutBatchNestedInput
}

export type BatchUncheckedUpdateWithoutEnrollmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_date?: Prisma.StringFieldUpdateOperationsInput | string
  end_date?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  recurringRule?: Prisma.BatchUpdaterecurringRuleInput | string[]
  coachingId?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subjects?: Prisma.SubjectUncheckedUpdateManyWithoutBatchesNestedInput
  assignedTeachers?: Prisma.UserUncheckedUpdateManyWithoutBatchesNestedInput
  demoClasses?: Prisma.DemoClassUncheckedUpdateManyWithoutBatchNestedInput
}

export type BatchUpdateWithoutAssignedTeachersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_date?: Prisma.StringFieldUpdateOperationsInput | string
  end_date?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  recurringRule?: Prisma.BatchUpdaterecurringRuleInput | string[]
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subjects?: Prisma.SubjectUpdateManyWithoutBatchesNestedInput
  coaching?: Prisma.CoachingCenterUpdateOneRequiredWithoutBatchesNestedInput
  demoClasses?: Prisma.DemoClassUpdateManyWithoutBatchNestedInput
  enrollments?: Prisma.EnrollmentUpdateManyWithoutBatchNestedInput
}

export type BatchUncheckedUpdateWithoutAssignedTeachersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_date?: Prisma.StringFieldUpdateOperationsInput | string
  end_date?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  recurringRule?: Prisma.BatchUpdaterecurringRuleInput | string[]
  coachingId?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subjects?: Prisma.SubjectUncheckedUpdateManyWithoutBatchesNestedInput
  demoClasses?: Prisma.DemoClassUncheckedUpdateManyWithoutBatchNestedInput
  enrollments?: Prisma.EnrollmentUncheckedUpdateManyWithoutBatchNestedInput
}

export type BatchUncheckedUpdateManyWithoutAssignedTeachersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_date?: Prisma.StringFieldUpdateOperationsInput | string
  end_date?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  recurringRule?: Prisma.BatchUpdaterecurringRuleInput | string[]
  coachingId?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BatchCreateManyCoachingInput = {
  id?: string
  name: string
  coverImage?: string | null
  start_date: string
  end_date: string
  capacity: number
  price: number
  recurringRule?: Prisma.BatchCreaterecurringRuleInput | string[]
  bio?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BatchUpdateWithoutCoachingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_date?: Prisma.StringFieldUpdateOperationsInput | string
  end_date?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  recurringRule?: Prisma.BatchUpdaterecurringRuleInput | string[]
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subjects?: Prisma.SubjectUpdateManyWithoutBatchesNestedInput
  assignedTeachers?: Prisma.UserUpdateManyWithoutBatchesNestedInput
  demoClasses?: Prisma.DemoClassUpdateManyWithoutBatchNestedInput
  enrollments?: Prisma.EnrollmentUpdateManyWithoutBatchNestedInput
}

export type BatchUncheckedUpdateWithoutCoachingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_date?: Prisma.StringFieldUpdateOperationsInput | string
  end_date?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  recurringRule?: Prisma.BatchUpdaterecurringRuleInput | string[]
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subjects?: Prisma.SubjectUncheckedUpdateManyWithoutBatchesNestedInput
  assignedTeachers?: Prisma.UserUncheckedUpdateManyWithoutBatchesNestedInput
  demoClasses?: Prisma.DemoClassUncheckedUpdateManyWithoutBatchNestedInput
  enrollments?: Prisma.EnrollmentUncheckedUpdateManyWithoutBatchNestedInput
}

export type BatchUncheckedUpdateManyWithoutCoachingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_date?: Prisma.StringFieldUpdateOperationsInput | string
  end_date?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  recurringRule?: Prisma.BatchUpdaterecurringRuleInput | string[]
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BatchUpdateWithoutSubjectsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_date?: Prisma.StringFieldUpdateOperationsInput | string
  end_date?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  recurringRule?: Prisma.BatchUpdaterecurringRuleInput | string[]
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assignedTeachers?: Prisma.UserUpdateManyWithoutBatchesNestedInput
  coaching?: Prisma.CoachingCenterUpdateOneRequiredWithoutBatchesNestedInput
  demoClasses?: Prisma.DemoClassUpdateManyWithoutBatchNestedInput
  enrollments?: Prisma.EnrollmentUpdateManyWithoutBatchNestedInput
}

export type BatchUncheckedUpdateWithoutSubjectsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_date?: Prisma.StringFieldUpdateOperationsInput | string
  end_date?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  recurringRule?: Prisma.BatchUpdaterecurringRuleInput | string[]
  coachingId?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assignedTeachers?: Prisma.UserUncheckedUpdateManyWithoutBatchesNestedInput
  demoClasses?: Prisma.DemoClassUncheckedUpdateManyWithoutBatchNestedInput
  enrollments?: Prisma.EnrollmentUncheckedUpdateManyWithoutBatchNestedInput
}

export type BatchUncheckedUpdateManyWithoutSubjectsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_date?: Prisma.StringFieldUpdateOperationsInput | string
  end_date?: Prisma.StringFieldUpdateOperationsInput | string
  capacity?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  recurringRule?: Prisma.BatchUpdaterecurringRuleInput | string[]
  coachingId?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type BatchCountOutputType
 */

export type BatchCountOutputType = {
  subjects: number
  assignedTeachers: number
  demoClasses: number
  enrollments: number
}

export type BatchCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subjects?: boolean | BatchCountOutputTypeCountSubjectsArgs
  assignedTeachers?: boolean | BatchCountOutputTypeCountAssignedTeachersArgs
  demoClasses?: boolean | BatchCountOutputTypeCountDemoClassesArgs
  enrollments?: boolean | BatchCountOutputTypeCountEnrollmentsArgs
}

/**
 * BatchCountOutputType without action
 */
export type BatchCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BatchCountOutputType
   */
  select?: Prisma.BatchCountOutputTypeSelect<ExtArgs> | null
}

/**
 * BatchCountOutputType without action
 */
export type BatchCountOutputTypeCountSubjectsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SubjectWhereInput
}

/**
 * BatchCountOutputType without action
 */
export type BatchCountOutputTypeCountAssignedTeachersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
}

/**
 * BatchCountOutputType without action
 */
export type BatchCountOutputTypeCountDemoClassesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DemoClassWhereInput
}

/**
 * BatchCountOutputType without action
 */
export type BatchCountOutputTypeCountEnrollmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EnrollmentWhereInput
}


export type BatchSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  coverImage?: boolean
  start_date?: boolean
  end_date?: boolean
  capacity?: boolean
  price?: boolean
  recurringRule?: boolean
  coachingId?: boolean
  bio?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  subjects?: boolean | Prisma.Batch$subjectsArgs<ExtArgs>
  assignedTeachers?: boolean | Prisma.Batch$assignedTeachersArgs<ExtArgs>
  coaching?: boolean | Prisma.CoachingCenterDefaultArgs<ExtArgs>
  demoClasses?: boolean | Prisma.Batch$demoClassesArgs<ExtArgs>
  enrollments?: boolean | Prisma.Batch$enrollmentsArgs<ExtArgs>
  _count?: boolean | Prisma.BatchCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["batch"]>

export type BatchSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  coverImage?: boolean
  start_date?: boolean
  end_date?: boolean
  capacity?: boolean
  price?: boolean
  recurringRule?: boolean
  coachingId?: boolean
  bio?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  coaching?: boolean | Prisma.CoachingCenterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["batch"]>

export type BatchSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  coverImage?: boolean
  start_date?: boolean
  end_date?: boolean
  capacity?: boolean
  price?: boolean
  recurringRule?: boolean
  coachingId?: boolean
  bio?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  coaching?: boolean | Prisma.CoachingCenterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["batch"]>

export type BatchSelectScalar = {
  id?: boolean
  name?: boolean
  coverImage?: boolean
  start_date?: boolean
  end_date?: boolean
  capacity?: boolean
  price?: boolean
  recurringRule?: boolean
  coachingId?: boolean
  bio?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type BatchOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "coverImage" | "start_date" | "end_date" | "capacity" | "price" | "recurringRule" | "coachingId" | "bio" | "createdAt" | "updatedAt", ExtArgs["result"]["batch"]>
export type BatchInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subjects?: boolean | Prisma.Batch$subjectsArgs<ExtArgs>
  assignedTeachers?: boolean | Prisma.Batch$assignedTeachersArgs<ExtArgs>
  coaching?: boolean | Prisma.CoachingCenterDefaultArgs<ExtArgs>
  demoClasses?: boolean | Prisma.Batch$demoClassesArgs<ExtArgs>
  enrollments?: boolean | Prisma.Batch$enrollmentsArgs<ExtArgs>
  _count?: boolean | Prisma.BatchCountOutputTypeDefaultArgs<ExtArgs>
}
export type BatchIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  coaching?: boolean | Prisma.CoachingCenterDefaultArgs<ExtArgs>
}
export type BatchIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  coaching?: boolean | Prisma.CoachingCenterDefaultArgs<ExtArgs>
}

export type $BatchPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Batch"
  objects: {
    subjects: Prisma.$SubjectPayload<ExtArgs>[]
    assignedTeachers: Prisma.$UserPayload<ExtArgs>[]
    coaching: Prisma.$CoachingCenterPayload<ExtArgs>
    demoClasses: Prisma.$DemoClassPayload<ExtArgs>[]
    enrollments: Prisma.$EnrollmentPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    coverImage: string | null
    start_date: string
    end_date: string
    capacity: number
    price: number
    recurringRule: string[]
    coachingId: string
    bio: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["batch"]>
  composites: {}
}

export type BatchGetPayload<S extends boolean | null | undefined | BatchDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BatchPayload, S>

export type BatchCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BatchFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BatchCountAggregateInputType | true
  }

export interface BatchDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Batch'], meta: { name: 'Batch' } }
  /**
   * Find zero or one Batch that matches the filter.
   * @param {BatchFindUniqueArgs} args - Arguments to find a Batch
   * @example
   * // Get one Batch
   * const batch = await prisma.batch.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BatchFindUniqueArgs>(args: Prisma.SelectSubset<T, BatchFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BatchClient<runtime.Types.Result.GetResult<Prisma.$BatchPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Batch that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BatchFindUniqueOrThrowArgs} args - Arguments to find a Batch
   * @example
   * // Get one Batch
   * const batch = await prisma.batch.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BatchFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BatchFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BatchClient<runtime.Types.Result.GetResult<Prisma.$BatchPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Batch that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BatchFindFirstArgs} args - Arguments to find a Batch
   * @example
   * // Get one Batch
   * const batch = await prisma.batch.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BatchFindFirstArgs>(args?: Prisma.SelectSubset<T, BatchFindFirstArgs<ExtArgs>>): Prisma.Prisma__BatchClient<runtime.Types.Result.GetResult<Prisma.$BatchPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Batch that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BatchFindFirstOrThrowArgs} args - Arguments to find a Batch
   * @example
   * // Get one Batch
   * const batch = await prisma.batch.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BatchFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BatchFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BatchClient<runtime.Types.Result.GetResult<Prisma.$BatchPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Batches that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BatchFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Batches
   * const batches = await prisma.batch.findMany()
   * 
   * // Get first 10 Batches
   * const batches = await prisma.batch.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const batchWithIdOnly = await prisma.batch.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BatchFindManyArgs>(args?: Prisma.SelectSubset<T, BatchFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BatchPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Batch.
   * @param {BatchCreateArgs} args - Arguments to create a Batch.
   * @example
   * // Create one Batch
   * const Batch = await prisma.batch.create({
   *   data: {
   *     // ... data to create a Batch
   *   }
   * })
   * 
   */
  create<T extends BatchCreateArgs>(args: Prisma.SelectSubset<T, BatchCreateArgs<ExtArgs>>): Prisma.Prisma__BatchClient<runtime.Types.Result.GetResult<Prisma.$BatchPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Batches.
   * @param {BatchCreateManyArgs} args - Arguments to create many Batches.
   * @example
   * // Create many Batches
   * const batch = await prisma.batch.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BatchCreateManyArgs>(args?: Prisma.SelectSubset<T, BatchCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Batches and returns the data saved in the database.
   * @param {BatchCreateManyAndReturnArgs} args - Arguments to create many Batches.
   * @example
   * // Create many Batches
   * const batch = await prisma.batch.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Batches and only return the `id`
   * const batchWithIdOnly = await prisma.batch.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BatchCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BatchCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BatchPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Batch.
   * @param {BatchDeleteArgs} args - Arguments to delete one Batch.
   * @example
   * // Delete one Batch
   * const Batch = await prisma.batch.delete({
   *   where: {
   *     // ... filter to delete one Batch
   *   }
   * })
   * 
   */
  delete<T extends BatchDeleteArgs>(args: Prisma.SelectSubset<T, BatchDeleteArgs<ExtArgs>>): Prisma.Prisma__BatchClient<runtime.Types.Result.GetResult<Prisma.$BatchPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Batch.
   * @param {BatchUpdateArgs} args - Arguments to update one Batch.
   * @example
   * // Update one Batch
   * const batch = await prisma.batch.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BatchUpdateArgs>(args: Prisma.SelectSubset<T, BatchUpdateArgs<ExtArgs>>): Prisma.Prisma__BatchClient<runtime.Types.Result.GetResult<Prisma.$BatchPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Batches.
   * @param {BatchDeleteManyArgs} args - Arguments to filter Batches to delete.
   * @example
   * // Delete a few Batches
   * const { count } = await prisma.batch.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BatchDeleteManyArgs>(args?: Prisma.SelectSubset<T, BatchDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Batches.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BatchUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Batches
   * const batch = await prisma.batch.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BatchUpdateManyArgs>(args: Prisma.SelectSubset<T, BatchUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Batches and returns the data updated in the database.
   * @param {BatchUpdateManyAndReturnArgs} args - Arguments to update many Batches.
   * @example
   * // Update many Batches
   * const batch = await prisma.batch.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Batches and only return the `id`
   * const batchWithIdOnly = await prisma.batch.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BatchUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BatchUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BatchPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Batch.
   * @param {BatchUpsertArgs} args - Arguments to update or create a Batch.
   * @example
   * // Update or create a Batch
   * const batch = await prisma.batch.upsert({
   *   create: {
   *     // ... data to create a Batch
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Batch we want to update
   *   }
   * })
   */
  upsert<T extends BatchUpsertArgs>(args: Prisma.SelectSubset<T, BatchUpsertArgs<ExtArgs>>): Prisma.Prisma__BatchClient<runtime.Types.Result.GetResult<Prisma.$BatchPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Batches.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BatchCountArgs} args - Arguments to filter Batches to count.
   * @example
   * // Count the number of Batches
   * const count = await prisma.batch.count({
   *   where: {
   *     // ... the filter for the Batches we want to count
   *   }
   * })
  **/
  count<T extends BatchCountArgs>(
    args?: Prisma.Subset<T, BatchCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BatchCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Batch.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BatchAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BatchAggregateArgs>(args: Prisma.Subset<T, BatchAggregateArgs>): Prisma.PrismaPromise<GetBatchAggregateType<T>>

  /**
   * Group by Batch.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BatchGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BatchGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BatchGroupByArgs['orderBy'] }
      : { orderBy?: BatchGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BatchGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBatchGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Batch model
 */
readonly fields: BatchFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Batch.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BatchClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  subjects<T extends Prisma.Batch$subjectsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Batch$subjectsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubjectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  assignedTeachers<T extends Prisma.Batch$assignedTeachersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Batch$assignedTeachersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  coaching<T extends Prisma.CoachingCenterDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CoachingCenterDefaultArgs<ExtArgs>>): Prisma.Prisma__CoachingCenterClient<runtime.Types.Result.GetResult<Prisma.$CoachingCenterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  demoClasses<T extends Prisma.Batch$demoClassesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Batch$demoClassesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DemoClassPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  enrollments<T extends Prisma.Batch$enrollmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Batch$enrollmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EnrollmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Batch model
 */
export interface BatchFieldRefs {
  readonly id: Prisma.FieldRef<"Batch", 'String'>
  readonly name: Prisma.FieldRef<"Batch", 'String'>
  readonly coverImage: Prisma.FieldRef<"Batch", 'String'>
  readonly start_date: Prisma.FieldRef<"Batch", 'String'>
  readonly end_date: Prisma.FieldRef<"Batch", 'String'>
  readonly capacity: Prisma.FieldRef<"Batch", 'Int'>
  readonly price: Prisma.FieldRef<"Batch", 'Int'>
  readonly recurringRule: Prisma.FieldRef<"Batch", 'String[]'>
  readonly coachingId: Prisma.FieldRef<"Batch", 'String'>
  readonly bio: Prisma.FieldRef<"Batch", 'String'>
  readonly createdAt: Prisma.FieldRef<"Batch", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Batch", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Batch findUnique
 */
export type BatchFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Batch
   */
  select?: Prisma.BatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Batch
   */
  omit?: Prisma.BatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchInclude<ExtArgs> | null
  /**
   * Filter, which Batch to fetch.
   */
  where: Prisma.BatchWhereUniqueInput
}

/**
 * Batch findUniqueOrThrow
 */
export type BatchFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Batch
   */
  select?: Prisma.BatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Batch
   */
  omit?: Prisma.BatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchInclude<ExtArgs> | null
  /**
   * Filter, which Batch to fetch.
   */
  where: Prisma.BatchWhereUniqueInput
}

/**
 * Batch findFirst
 */
export type BatchFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Batch
   */
  select?: Prisma.BatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Batch
   */
  omit?: Prisma.BatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchInclude<ExtArgs> | null
  /**
   * Filter, which Batch to fetch.
   */
  where?: Prisma.BatchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Batches to fetch.
   */
  orderBy?: Prisma.BatchOrderByWithRelationInput | Prisma.BatchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Batches.
   */
  cursor?: Prisma.BatchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Batches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Batches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Batches.
   */
  distinct?: Prisma.BatchScalarFieldEnum | Prisma.BatchScalarFieldEnum[]
}

/**
 * Batch findFirstOrThrow
 */
export type BatchFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Batch
   */
  select?: Prisma.BatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Batch
   */
  omit?: Prisma.BatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchInclude<ExtArgs> | null
  /**
   * Filter, which Batch to fetch.
   */
  where?: Prisma.BatchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Batches to fetch.
   */
  orderBy?: Prisma.BatchOrderByWithRelationInput | Prisma.BatchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Batches.
   */
  cursor?: Prisma.BatchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Batches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Batches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Batches.
   */
  distinct?: Prisma.BatchScalarFieldEnum | Prisma.BatchScalarFieldEnum[]
}

/**
 * Batch findMany
 */
export type BatchFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Batch
   */
  select?: Prisma.BatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Batch
   */
  omit?: Prisma.BatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchInclude<ExtArgs> | null
  /**
   * Filter, which Batches to fetch.
   */
  where?: Prisma.BatchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Batches to fetch.
   */
  orderBy?: Prisma.BatchOrderByWithRelationInput | Prisma.BatchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Batches.
   */
  cursor?: Prisma.BatchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Batches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Batches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Batches.
   */
  distinct?: Prisma.BatchScalarFieldEnum | Prisma.BatchScalarFieldEnum[]
}

/**
 * Batch create
 */
export type BatchCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Batch
   */
  select?: Prisma.BatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Batch
   */
  omit?: Prisma.BatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchInclude<ExtArgs> | null
  /**
   * The data needed to create a Batch.
   */
  data: Prisma.XOR<Prisma.BatchCreateInput, Prisma.BatchUncheckedCreateInput>
}

/**
 * Batch createMany
 */
export type BatchCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Batches.
   */
  data: Prisma.BatchCreateManyInput | Prisma.BatchCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Batch createManyAndReturn
 */
export type BatchCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Batch
   */
  select?: Prisma.BatchSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Batch
   */
  omit?: Prisma.BatchOmit<ExtArgs> | null
  /**
   * The data used to create many Batches.
   */
  data: Prisma.BatchCreateManyInput | Prisma.BatchCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Batch update
 */
export type BatchUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Batch
   */
  select?: Prisma.BatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Batch
   */
  omit?: Prisma.BatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchInclude<ExtArgs> | null
  /**
   * The data needed to update a Batch.
   */
  data: Prisma.XOR<Prisma.BatchUpdateInput, Prisma.BatchUncheckedUpdateInput>
  /**
   * Choose, which Batch to update.
   */
  where: Prisma.BatchWhereUniqueInput
}

/**
 * Batch updateMany
 */
export type BatchUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Batches.
   */
  data: Prisma.XOR<Prisma.BatchUpdateManyMutationInput, Prisma.BatchUncheckedUpdateManyInput>
  /**
   * Filter which Batches to update
   */
  where?: Prisma.BatchWhereInput
  /**
   * Limit how many Batches to update.
   */
  limit?: number
}

/**
 * Batch updateManyAndReturn
 */
export type BatchUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Batch
   */
  select?: Prisma.BatchSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Batch
   */
  omit?: Prisma.BatchOmit<ExtArgs> | null
  /**
   * The data used to update Batches.
   */
  data: Prisma.XOR<Prisma.BatchUpdateManyMutationInput, Prisma.BatchUncheckedUpdateManyInput>
  /**
   * Filter which Batches to update
   */
  where?: Prisma.BatchWhereInput
  /**
   * Limit how many Batches to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Batch upsert
 */
export type BatchUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Batch
   */
  select?: Prisma.BatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Batch
   */
  omit?: Prisma.BatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchInclude<ExtArgs> | null
  /**
   * The filter to search for the Batch to update in case it exists.
   */
  where: Prisma.BatchWhereUniqueInput
  /**
   * In case the Batch found by the `where` argument doesn't exist, create a new Batch with this data.
   */
  create: Prisma.XOR<Prisma.BatchCreateInput, Prisma.BatchUncheckedCreateInput>
  /**
   * In case the Batch was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BatchUpdateInput, Prisma.BatchUncheckedUpdateInput>
}

/**
 * Batch delete
 */
export type BatchDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Batch
   */
  select?: Prisma.BatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Batch
   */
  omit?: Prisma.BatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchInclude<ExtArgs> | null
  /**
   * Filter which Batch to delete.
   */
  where: Prisma.BatchWhereUniqueInput
}

/**
 * Batch deleteMany
 */
export type BatchDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Batches to delete
   */
  where?: Prisma.BatchWhereInput
  /**
   * Limit how many Batches to delete.
   */
  limit?: number
}

/**
 * Batch.subjects
 */
export type Batch$subjectsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Subject
   */
  select?: Prisma.SubjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Subject
   */
  omit?: Prisma.SubjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubjectInclude<ExtArgs> | null
  where?: Prisma.SubjectWhereInput
  orderBy?: Prisma.SubjectOrderByWithRelationInput | Prisma.SubjectOrderByWithRelationInput[]
  cursor?: Prisma.SubjectWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SubjectScalarFieldEnum | Prisma.SubjectScalarFieldEnum[]
}

/**
 * Batch.assignedTeachers
 */
export type Batch$assignedTeachersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  cursor?: Prisma.UserWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * Batch.demoClasses
 */
export type Batch$demoClassesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DemoClass
   */
  select?: Prisma.DemoClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DemoClass
   */
  omit?: Prisma.DemoClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemoClassInclude<ExtArgs> | null
  where?: Prisma.DemoClassWhereInput
  orderBy?: Prisma.DemoClassOrderByWithRelationInput | Prisma.DemoClassOrderByWithRelationInput[]
  cursor?: Prisma.DemoClassWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DemoClassScalarFieldEnum | Prisma.DemoClassScalarFieldEnum[]
}

/**
 * Batch.enrollments
 */
export type Batch$enrollmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Enrollment
   */
  select?: Prisma.EnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Enrollment
   */
  omit?: Prisma.EnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EnrollmentInclude<ExtArgs> | null
  where?: Prisma.EnrollmentWhereInput
  orderBy?: Prisma.EnrollmentOrderByWithRelationInput | Prisma.EnrollmentOrderByWithRelationInput[]
  cursor?: Prisma.EnrollmentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EnrollmentScalarFieldEnum | Prisma.EnrollmentScalarFieldEnum[]
}

/**
 * Batch without action
 */
export type BatchDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Batch
   */
  select?: Prisma.BatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Batch
   */
  omit?: Prisma.BatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchInclude<ExtArgs> | null
}
