
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DemoClass` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model DemoClass
 * 
 */
export type DemoClassModel = runtime.Types.Result.DefaultSelection<Prisma.$DemoClassPayload>

export type AggregateDemoClass = {
  _count: DemoClassCountAggregateOutputType | null
  _min: DemoClassMinAggregateOutputType | null
  _max: DemoClassMaxAggregateOutputType | null
}

export type DemoClassMinAggregateOutputType = {
  id: string | null
  title: string | null
  videoURL: string | null
  subjectId: string | null
  batchId: string | null
  userId: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DemoClassMaxAggregateOutputType = {
  id: string | null
  title: string | null
  videoURL: string | null
  subjectId: string | null
  batchId: string | null
  userId: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DemoClassCountAggregateOutputType = {
  id: number
  title: number
  videoURL: number
  subjectId: number
  batchId: number
  userId: number
  status: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type DemoClassMinAggregateInputType = {
  id?: true
  title?: true
  videoURL?: true
  subjectId?: true
  batchId?: true
  userId?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type DemoClassMaxAggregateInputType = {
  id?: true
  title?: true
  videoURL?: true
  subjectId?: true
  batchId?: true
  userId?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type DemoClassCountAggregateInputType = {
  id?: true
  title?: true
  videoURL?: true
  subjectId?: true
  batchId?: true
  userId?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type DemoClassAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DemoClass to aggregate.
   */
  where?: Prisma.DemoClassWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DemoClasses to fetch.
   */
  orderBy?: Prisma.DemoClassOrderByWithRelationInput | Prisma.DemoClassOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DemoClassWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DemoClasses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DemoClasses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DemoClasses
  **/
  _count?: true | DemoClassCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DemoClassMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DemoClassMaxAggregateInputType
}

export type GetDemoClassAggregateType<T extends DemoClassAggregateArgs> = {
      [P in keyof T & keyof AggregateDemoClass]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDemoClass[P]>
    : Prisma.GetScalarType<T[P], AggregateDemoClass[P]>
}




export type DemoClassGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DemoClassWhereInput
  orderBy?: Prisma.DemoClassOrderByWithAggregationInput | Prisma.DemoClassOrderByWithAggregationInput[]
  by: Prisma.DemoClassScalarFieldEnum[] | Prisma.DemoClassScalarFieldEnum
  having?: Prisma.DemoClassScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DemoClassCountAggregateInputType | true
  _min?: DemoClassMinAggregateInputType
  _max?: DemoClassMaxAggregateInputType
}

export type DemoClassGroupByOutputType = {
  id: string
  title: string
  videoURL: string
  subjectId: string
  batchId: string | null
  userId: string
  status: string
  createdAt: Date
  updatedAt: Date
  _count: DemoClassCountAggregateOutputType | null
  _min: DemoClassMinAggregateOutputType | null
  _max: DemoClassMaxAggregateOutputType | null
}

export type GetDemoClassGroupByPayload<T extends DemoClassGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DemoClassGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DemoClassGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DemoClassGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DemoClassGroupByOutputType[P]>
      }
    >
  >



export type DemoClassWhereInput = {
  AND?: Prisma.DemoClassWhereInput | Prisma.DemoClassWhereInput[]
  OR?: Prisma.DemoClassWhereInput[]
  NOT?: Prisma.DemoClassWhereInput | Prisma.DemoClassWhereInput[]
  id?: Prisma.StringFilter<"DemoClass"> | string
  title?: Prisma.StringFilter<"DemoClass"> | string
  videoURL?: Prisma.StringFilter<"DemoClass"> | string
  subjectId?: Prisma.StringFilter<"DemoClass"> | string
  batchId?: Prisma.StringNullableFilter<"DemoClass"> | string | null
  userId?: Prisma.StringFilter<"DemoClass"> | string
  status?: Prisma.StringFilter<"DemoClass"> | string
  createdAt?: Prisma.DateTimeFilter<"DemoClass"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DemoClass"> | Date | string
  subject?: Prisma.XOR<Prisma.SubjectScalarRelationFilter, Prisma.SubjectWhereInput>
  batch?: Prisma.XOR<Prisma.BatchNullableScalarRelationFilter, Prisma.BatchWhereInput> | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type DemoClassOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  videoURL?: Prisma.SortOrder
  subjectId?: Prisma.SortOrder
  batchId?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  subject?: Prisma.SubjectOrderByWithRelationInput
  batch?: Prisma.BatchOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type DemoClassWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DemoClassWhereInput | Prisma.DemoClassWhereInput[]
  OR?: Prisma.DemoClassWhereInput[]
  NOT?: Prisma.DemoClassWhereInput | Prisma.DemoClassWhereInput[]
  title?: Prisma.StringFilter<"DemoClass"> | string
  videoURL?: Prisma.StringFilter<"DemoClass"> | string
  subjectId?: Prisma.StringFilter<"DemoClass"> | string
  batchId?: Prisma.StringNullableFilter<"DemoClass"> | string | null
  userId?: Prisma.StringFilter<"DemoClass"> | string
  status?: Prisma.StringFilter<"DemoClass"> | string
  createdAt?: Prisma.DateTimeFilter<"DemoClass"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DemoClass"> | Date | string
  subject?: Prisma.XOR<Prisma.SubjectScalarRelationFilter, Prisma.SubjectWhereInput>
  batch?: Prisma.XOR<Prisma.BatchNullableScalarRelationFilter, Prisma.BatchWhereInput> | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type DemoClassOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  videoURL?: Prisma.SortOrder
  subjectId?: Prisma.SortOrder
  batchId?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.DemoClassCountOrderByAggregateInput
  _max?: Prisma.DemoClassMaxOrderByAggregateInput
  _min?: Prisma.DemoClassMinOrderByAggregateInput
}

export type DemoClassScalarWhereWithAggregatesInput = {
  AND?: Prisma.DemoClassScalarWhereWithAggregatesInput | Prisma.DemoClassScalarWhereWithAggregatesInput[]
  OR?: Prisma.DemoClassScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DemoClassScalarWhereWithAggregatesInput | Prisma.DemoClassScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DemoClass"> | string
  title?: Prisma.StringWithAggregatesFilter<"DemoClass"> | string
  videoURL?: Prisma.StringWithAggregatesFilter<"DemoClass"> | string
  subjectId?: Prisma.StringWithAggregatesFilter<"DemoClass"> | string
  batchId?: Prisma.StringNullableWithAggregatesFilter<"DemoClass"> | string | null
  userId?: Prisma.StringWithAggregatesFilter<"DemoClass"> | string
  status?: Prisma.StringWithAggregatesFilter<"DemoClass"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"DemoClass"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"DemoClass"> | Date | string
}

export type DemoClassCreateInput = {
  id?: string
  title: string
  videoURL: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  subject: Prisma.SubjectCreateNestedOneWithoutDemoClassesInput
  batch?: Prisma.BatchCreateNestedOneWithoutDemoClassesInput
  user: Prisma.UserCreateNestedOneWithoutDemoClassesInput
}

export type DemoClassUncheckedCreateInput = {
  id?: string
  title: string
  videoURL: string
  subjectId: string
  batchId?: string | null
  userId: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DemoClassUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  videoURL?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subject?: Prisma.SubjectUpdateOneRequiredWithoutDemoClassesNestedInput
  batch?: Prisma.BatchUpdateOneWithoutDemoClassesNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutDemoClassesNestedInput
}

export type DemoClassUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  videoURL?: Prisma.StringFieldUpdateOperationsInput | string
  subjectId?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DemoClassCreateManyInput = {
  id?: string
  title: string
  videoURL: string
  subjectId: string
  batchId?: string | null
  userId: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DemoClassUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  videoURL?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DemoClassUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  videoURL?: Prisma.StringFieldUpdateOperationsInput | string
  subjectId?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DemoClassListRelationFilter = {
  every?: Prisma.DemoClassWhereInput
  some?: Prisma.DemoClassWhereInput
  none?: Prisma.DemoClassWhereInput
}

export type DemoClassOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DemoClassCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  videoURL?: Prisma.SortOrder
  subjectId?: Prisma.SortOrder
  batchId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DemoClassMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  videoURL?: Prisma.SortOrder
  subjectId?: Prisma.SortOrder
  batchId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DemoClassMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  videoURL?: Prisma.SortOrder
  subjectId?: Prisma.SortOrder
  batchId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DemoClassCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.DemoClassCreateWithoutUserInput, Prisma.DemoClassUncheckedCreateWithoutUserInput> | Prisma.DemoClassCreateWithoutUserInput[] | Prisma.DemoClassUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DemoClassCreateOrConnectWithoutUserInput | Prisma.DemoClassCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.DemoClassCreateManyUserInputEnvelope
  connect?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
}

export type DemoClassUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.DemoClassCreateWithoutUserInput, Prisma.DemoClassUncheckedCreateWithoutUserInput> | Prisma.DemoClassCreateWithoutUserInput[] | Prisma.DemoClassUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DemoClassCreateOrConnectWithoutUserInput | Prisma.DemoClassCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.DemoClassCreateManyUserInputEnvelope
  connect?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
}

export type DemoClassUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.DemoClassCreateWithoutUserInput, Prisma.DemoClassUncheckedCreateWithoutUserInput> | Prisma.DemoClassCreateWithoutUserInput[] | Prisma.DemoClassUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DemoClassCreateOrConnectWithoutUserInput | Prisma.DemoClassCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.DemoClassUpsertWithWhereUniqueWithoutUserInput | Prisma.DemoClassUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.DemoClassCreateManyUserInputEnvelope
  set?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  disconnect?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  delete?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  connect?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  update?: Prisma.DemoClassUpdateWithWhereUniqueWithoutUserInput | Prisma.DemoClassUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.DemoClassUpdateManyWithWhereWithoutUserInput | Prisma.DemoClassUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.DemoClassScalarWhereInput | Prisma.DemoClassScalarWhereInput[]
}

export type DemoClassUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.DemoClassCreateWithoutUserInput, Prisma.DemoClassUncheckedCreateWithoutUserInput> | Prisma.DemoClassCreateWithoutUserInput[] | Prisma.DemoClassUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DemoClassCreateOrConnectWithoutUserInput | Prisma.DemoClassCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.DemoClassUpsertWithWhereUniqueWithoutUserInput | Prisma.DemoClassUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.DemoClassCreateManyUserInputEnvelope
  set?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  disconnect?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  delete?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  connect?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  update?: Prisma.DemoClassUpdateWithWhereUniqueWithoutUserInput | Prisma.DemoClassUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.DemoClassUpdateManyWithWhereWithoutUserInput | Prisma.DemoClassUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.DemoClassScalarWhereInput | Prisma.DemoClassScalarWhereInput[]
}

export type DemoClassCreateNestedManyWithoutSubjectInput = {
  create?: Prisma.XOR<Prisma.DemoClassCreateWithoutSubjectInput, Prisma.DemoClassUncheckedCreateWithoutSubjectInput> | Prisma.DemoClassCreateWithoutSubjectInput[] | Prisma.DemoClassUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.DemoClassCreateOrConnectWithoutSubjectInput | Prisma.DemoClassCreateOrConnectWithoutSubjectInput[]
  createMany?: Prisma.DemoClassCreateManySubjectInputEnvelope
  connect?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
}

export type DemoClassUncheckedCreateNestedManyWithoutSubjectInput = {
  create?: Prisma.XOR<Prisma.DemoClassCreateWithoutSubjectInput, Prisma.DemoClassUncheckedCreateWithoutSubjectInput> | Prisma.DemoClassCreateWithoutSubjectInput[] | Prisma.DemoClassUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.DemoClassCreateOrConnectWithoutSubjectInput | Prisma.DemoClassCreateOrConnectWithoutSubjectInput[]
  createMany?: Prisma.DemoClassCreateManySubjectInputEnvelope
  connect?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
}

export type DemoClassUpdateManyWithoutSubjectNestedInput = {
  create?: Prisma.XOR<Prisma.DemoClassCreateWithoutSubjectInput, Prisma.DemoClassUncheckedCreateWithoutSubjectInput> | Prisma.DemoClassCreateWithoutSubjectInput[] | Prisma.DemoClassUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.DemoClassCreateOrConnectWithoutSubjectInput | Prisma.DemoClassCreateOrConnectWithoutSubjectInput[]
  upsert?: Prisma.DemoClassUpsertWithWhereUniqueWithoutSubjectInput | Prisma.DemoClassUpsertWithWhereUniqueWithoutSubjectInput[]
  createMany?: Prisma.DemoClassCreateManySubjectInputEnvelope
  set?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  disconnect?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  delete?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  connect?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  update?: Prisma.DemoClassUpdateWithWhereUniqueWithoutSubjectInput | Prisma.DemoClassUpdateWithWhereUniqueWithoutSubjectInput[]
  updateMany?: Prisma.DemoClassUpdateManyWithWhereWithoutSubjectInput | Prisma.DemoClassUpdateManyWithWhereWithoutSubjectInput[]
  deleteMany?: Prisma.DemoClassScalarWhereInput | Prisma.DemoClassScalarWhereInput[]
}

export type DemoClassUncheckedUpdateManyWithoutSubjectNestedInput = {
  create?: Prisma.XOR<Prisma.DemoClassCreateWithoutSubjectInput, Prisma.DemoClassUncheckedCreateWithoutSubjectInput> | Prisma.DemoClassCreateWithoutSubjectInput[] | Prisma.DemoClassUncheckedCreateWithoutSubjectInput[]
  connectOrCreate?: Prisma.DemoClassCreateOrConnectWithoutSubjectInput | Prisma.DemoClassCreateOrConnectWithoutSubjectInput[]
  upsert?: Prisma.DemoClassUpsertWithWhereUniqueWithoutSubjectInput | Prisma.DemoClassUpsertWithWhereUniqueWithoutSubjectInput[]
  createMany?: Prisma.DemoClassCreateManySubjectInputEnvelope
  set?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  disconnect?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  delete?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  connect?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  update?: Prisma.DemoClassUpdateWithWhereUniqueWithoutSubjectInput | Prisma.DemoClassUpdateWithWhereUniqueWithoutSubjectInput[]
  updateMany?: Prisma.DemoClassUpdateManyWithWhereWithoutSubjectInput | Prisma.DemoClassUpdateManyWithWhereWithoutSubjectInput[]
  deleteMany?: Prisma.DemoClassScalarWhereInput | Prisma.DemoClassScalarWhereInput[]
}

export type DemoClassCreateNestedManyWithoutBatchInput = {
  create?: Prisma.XOR<Prisma.DemoClassCreateWithoutBatchInput, Prisma.DemoClassUncheckedCreateWithoutBatchInput> | Prisma.DemoClassCreateWithoutBatchInput[] | Prisma.DemoClassUncheckedCreateWithoutBatchInput[]
  connectOrCreate?: Prisma.DemoClassCreateOrConnectWithoutBatchInput | Prisma.DemoClassCreateOrConnectWithoutBatchInput[]
  createMany?: Prisma.DemoClassCreateManyBatchInputEnvelope
  connect?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
}

export type DemoClassUncheckedCreateNestedManyWithoutBatchInput = {
  create?: Prisma.XOR<Prisma.DemoClassCreateWithoutBatchInput, Prisma.DemoClassUncheckedCreateWithoutBatchInput> | Prisma.DemoClassCreateWithoutBatchInput[] | Prisma.DemoClassUncheckedCreateWithoutBatchInput[]
  connectOrCreate?: Prisma.DemoClassCreateOrConnectWithoutBatchInput | Prisma.DemoClassCreateOrConnectWithoutBatchInput[]
  createMany?: Prisma.DemoClassCreateManyBatchInputEnvelope
  connect?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
}

export type DemoClassUpdateManyWithoutBatchNestedInput = {
  create?: Prisma.XOR<Prisma.DemoClassCreateWithoutBatchInput, Prisma.DemoClassUncheckedCreateWithoutBatchInput> | Prisma.DemoClassCreateWithoutBatchInput[] | Prisma.DemoClassUncheckedCreateWithoutBatchInput[]
  connectOrCreate?: Prisma.DemoClassCreateOrConnectWithoutBatchInput | Prisma.DemoClassCreateOrConnectWithoutBatchInput[]
  upsert?: Prisma.DemoClassUpsertWithWhereUniqueWithoutBatchInput | Prisma.DemoClassUpsertWithWhereUniqueWithoutBatchInput[]
  createMany?: Prisma.DemoClassCreateManyBatchInputEnvelope
  set?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  disconnect?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  delete?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  connect?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  update?: Prisma.DemoClassUpdateWithWhereUniqueWithoutBatchInput | Prisma.DemoClassUpdateWithWhereUniqueWithoutBatchInput[]
  updateMany?: Prisma.DemoClassUpdateManyWithWhereWithoutBatchInput | Prisma.DemoClassUpdateManyWithWhereWithoutBatchInput[]
  deleteMany?: Prisma.DemoClassScalarWhereInput | Prisma.DemoClassScalarWhereInput[]
}

export type DemoClassUncheckedUpdateManyWithoutBatchNestedInput = {
  create?: Prisma.XOR<Prisma.DemoClassCreateWithoutBatchInput, Prisma.DemoClassUncheckedCreateWithoutBatchInput> | Prisma.DemoClassCreateWithoutBatchInput[] | Prisma.DemoClassUncheckedCreateWithoutBatchInput[]
  connectOrCreate?: Prisma.DemoClassCreateOrConnectWithoutBatchInput | Prisma.DemoClassCreateOrConnectWithoutBatchInput[]
  upsert?: Prisma.DemoClassUpsertWithWhereUniqueWithoutBatchInput | Prisma.DemoClassUpsertWithWhereUniqueWithoutBatchInput[]
  createMany?: Prisma.DemoClassCreateManyBatchInputEnvelope
  set?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  disconnect?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  delete?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  connect?: Prisma.DemoClassWhereUniqueInput | Prisma.DemoClassWhereUniqueInput[]
  update?: Prisma.DemoClassUpdateWithWhereUniqueWithoutBatchInput | Prisma.DemoClassUpdateWithWhereUniqueWithoutBatchInput[]
  updateMany?: Prisma.DemoClassUpdateManyWithWhereWithoutBatchInput | Prisma.DemoClassUpdateManyWithWhereWithoutBatchInput[]
  deleteMany?: Prisma.DemoClassScalarWhereInput | Prisma.DemoClassScalarWhereInput[]
}

export type DemoClassCreateWithoutUserInput = {
  id?: string
  title: string
  videoURL: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  subject: Prisma.SubjectCreateNestedOneWithoutDemoClassesInput
  batch?: Prisma.BatchCreateNestedOneWithoutDemoClassesInput
}

export type DemoClassUncheckedCreateWithoutUserInput = {
  id?: string
  title: string
  videoURL: string
  subjectId: string
  batchId?: string | null
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DemoClassCreateOrConnectWithoutUserInput = {
  where: Prisma.DemoClassWhereUniqueInput
  create: Prisma.XOR<Prisma.DemoClassCreateWithoutUserInput, Prisma.DemoClassUncheckedCreateWithoutUserInput>
}

export type DemoClassCreateManyUserInputEnvelope = {
  data: Prisma.DemoClassCreateManyUserInput | Prisma.DemoClassCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type DemoClassUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.DemoClassWhereUniqueInput
  update: Prisma.XOR<Prisma.DemoClassUpdateWithoutUserInput, Prisma.DemoClassUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.DemoClassCreateWithoutUserInput, Prisma.DemoClassUncheckedCreateWithoutUserInput>
}

export type DemoClassUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.DemoClassWhereUniqueInput
  data: Prisma.XOR<Prisma.DemoClassUpdateWithoutUserInput, Prisma.DemoClassUncheckedUpdateWithoutUserInput>
}

export type DemoClassUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.DemoClassScalarWhereInput
  data: Prisma.XOR<Prisma.DemoClassUpdateManyMutationInput, Prisma.DemoClassUncheckedUpdateManyWithoutUserInput>
}

export type DemoClassScalarWhereInput = {
  AND?: Prisma.DemoClassScalarWhereInput | Prisma.DemoClassScalarWhereInput[]
  OR?: Prisma.DemoClassScalarWhereInput[]
  NOT?: Prisma.DemoClassScalarWhereInput | Prisma.DemoClassScalarWhereInput[]
  id?: Prisma.StringFilter<"DemoClass"> | string
  title?: Prisma.StringFilter<"DemoClass"> | string
  videoURL?: Prisma.StringFilter<"DemoClass"> | string
  subjectId?: Prisma.StringFilter<"DemoClass"> | string
  batchId?: Prisma.StringNullableFilter<"DemoClass"> | string | null
  userId?: Prisma.StringFilter<"DemoClass"> | string
  status?: Prisma.StringFilter<"DemoClass"> | string
  createdAt?: Prisma.DateTimeFilter<"DemoClass"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DemoClass"> | Date | string
}

export type DemoClassCreateWithoutSubjectInput = {
  id?: string
  title: string
  videoURL: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  batch?: Prisma.BatchCreateNestedOneWithoutDemoClassesInput
  user: Prisma.UserCreateNestedOneWithoutDemoClassesInput
}

export type DemoClassUncheckedCreateWithoutSubjectInput = {
  id?: string
  title: string
  videoURL: string
  batchId?: string | null
  userId: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DemoClassCreateOrConnectWithoutSubjectInput = {
  where: Prisma.DemoClassWhereUniqueInput
  create: Prisma.XOR<Prisma.DemoClassCreateWithoutSubjectInput, Prisma.DemoClassUncheckedCreateWithoutSubjectInput>
}

export type DemoClassCreateManySubjectInputEnvelope = {
  data: Prisma.DemoClassCreateManySubjectInput | Prisma.DemoClassCreateManySubjectInput[]
  skipDuplicates?: boolean
}

export type DemoClassUpsertWithWhereUniqueWithoutSubjectInput = {
  where: Prisma.DemoClassWhereUniqueInput
  update: Prisma.XOR<Prisma.DemoClassUpdateWithoutSubjectInput, Prisma.DemoClassUncheckedUpdateWithoutSubjectInput>
  create: Prisma.XOR<Prisma.DemoClassCreateWithoutSubjectInput, Prisma.DemoClassUncheckedCreateWithoutSubjectInput>
}

export type DemoClassUpdateWithWhereUniqueWithoutSubjectInput = {
  where: Prisma.DemoClassWhereUniqueInput
  data: Prisma.XOR<Prisma.DemoClassUpdateWithoutSubjectInput, Prisma.DemoClassUncheckedUpdateWithoutSubjectInput>
}

export type DemoClassUpdateManyWithWhereWithoutSubjectInput = {
  where: Prisma.DemoClassScalarWhereInput
  data: Prisma.XOR<Prisma.DemoClassUpdateManyMutationInput, Prisma.DemoClassUncheckedUpdateManyWithoutSubjectInput>
}

export type DemoClassCreateWithoutBatchInput = {
  id?: string
  title: string
  videoURL: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  subject: Prisma.SubjectCreateNestedOneWithoutDemoClassesInput
  user: Prisma.UserCreateNestedOneWithoutDemoClassesInput
}

export type DemoClassUncheckedCreateWithoutBatchInput = {
  id?: string
  title: string
  videoURL: string
  subjectId: string
  userId: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DemoClassCreateOrConnectWithoutBatchInput = {
  where: Prisma.DemoClassWhereUniqueInput
  create: Prisma.XOR<Prisma.DemoClassCreateWithoutBatchInput, Prisma.DemoClassUncheckedCreateWithoutBatchInput>
}

export type DemoClassCreateManyBatchInputEnvelope = {
  data: Prisma.DemoClassCreateManyBatchInput | Prisma.DemoClassCreateManyBatchInput[]
  skipDuplicates?: boolean
}

export type DemoClassUpsertWithWhereUniqueWithoutBatchInput = {
  where: Prisma.DemoClassWhereUniqueInput
  update: Prisma.XOR<Prisma.DemoClassUpdateWithoutBatchInput, Prisma.DemoClassUncheckedUpdateWithoutBatchInput>
  create: Prisma.XOR<Prisma.DemoClassCreateWithoutBatchInput, Prisma.DemoClassUncheckedCreateWithoutBatchInput>
}

export type DemoClassUpdateWithWhereUniqueWithoutBatchInput = {
  where: Prisma.DemoClassWhereUniqueInput
  data: Prisma.XOR<Prisma.DemoClassUpdateWithoutBatchInput, Prisma.DemoClassUncheckedUpdateWithoutBatchInput>
}

export type DemoClassUpdateManyWithWhereWithoutBatchInput = {
  where: Prisma.DemoClassScalarWhereInput
  data: Prisma.XOR<Prisma.DemoClassUpdateManyMutationInput, Prisma.DemoClassUncheckedUpdateManyWithoutBatchInput>
}

export type DemoClassCreateManyUserInput = {
  id?: string
  title: string
  videoURL: string
  subjectId: string
  batchId?: string | null
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DemoClassUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  videoURL?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subject?: Prisma.SubjectUpdateOneRequiredWithoutDemoClassesNestedInput
  batch?: Prisma.BatchUpdateOneWithoutDemoClassesNestedInput
}

export type DemoClassUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  videoURL?: Prisma.StringFieldUpdateOperationsInput | string
  subjectId?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DemoClassUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  videoURL?: Prisma.StringFieldUpdateOperationsInput | string
  subjectId?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DemoClassCreateManySubjectInput = {
  id?: string
  title: string
  videoURL: string
  batchId?: string | null
  userId: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DemoClassUpdateWithoutSubjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  videoURL?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  batch?: Prisma.BatchUpdateOneWithoutDemoClassesNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutDemoClassesNestedInput
}

export type DemoClassUncheckedUpdateWithoutSubjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  videoURL?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DemoClassUncheckedUpdateManyWithoutSubjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  videoURL?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DemoClassCreateManyBatchInput = {
  id?: string
  title: string
  videoURL: string
  subjectId: string
  userId: string
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DemoClassUpdateWithoutBatchInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  videoURL?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subject?: Prisma.SubjectUpdateOneRequiredWithoutDemoClassesNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutDemoClassesNestedInput
}

export type DemoClassUncheckedUpdateWithoutBatchInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  videoURL?: Prisma.StringFieldUpdateOperationsInput | string
  subjectId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DemoClassUncheckedUpdateManyWithoutBatchInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  videoURL?: Prisma.StringFieldUpdateOperationsInput | string
  subjectId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type DemoClassSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  videoURL?: boolean
  subjectId?: boolean
  batchId?: boolean
  userId?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  subject?: boolean | Prisma.SubjectDefaultArgs<ExtArgs>
  batch?: boolean | Prisma.DemoClass$batchArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["demoClass"]>

export type DemoClassSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  videoURL?: boolean
  subjectId?: boolean
  batchId?: boolean
  userId?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  subject?: boolean | Prisma.SubjectDefaultArgs<ExtArgs>
  batch?: boolean | Prisma.DemoClass$batchArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["demoClass"]>

export type DemoClassSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  videoURL?: boolean
  subjectId?: boolean
  batchId?: boolean
  userId?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  subject?: boolean | Prisma.SubjectDefaultArgs<ExtArgs>
  batch?: boolean | Prisma.DemoClass$batchArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["demoClass"]>

export type DemoClassSelectScalar = {
  id?: boolean
  title?: boolean
  videoURL?: boolean
  subjectId?: boolean
  batchId?: boolean
  userId?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type DemoClassOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "videoURL" | "subjectId" | "batchId" | "userId" | "status" | "createdAt" | "updatedAt", ExtArgs["result"]["demoClass"]>
export type DemoClassInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subject?: boolean | Prisma.SubjectDefaultArgs<ExtArgs>
  batch?: boolean | Prisma.DemoClass$batchArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type DemoClassIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subject?: boolean | Prisma.SubjectDefaultArgs<ExtArgs>
  batch?: boolean | Prisma.DemoClass$batchArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type DemoClassIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subject?: boolean | Prisma.SubjectDefaultArgs<ExtArgs>
  batch?: boolean | Prisma.DemoClass$batchArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $DemoClassPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DemoClass"
  objects: {
    subject: Prisma.$SubjectPayload<ExtArgs>
    batch: Prisma.$BatchPayload<ExtArgs> | null
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    videoURL: string
    subjectId: string
    batchId: string | null
    userId: string
    status: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["demoClass"]>
  composites: {}
}

export type DemoClassGetPayload<S extends boolean | null | undefined | DemoClassDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DemoClassPayload, S>

export type DemoClassCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DemoClassFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DemoClassCountAggregateInputType | true
  }

export interface DemoClassDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DemoClass'], meta: { name: 'DemoClass' } }
  /**
   * Find zero or one DemoClass that matches the filter.
   * @param {DemoClassFindUniqueArgs} args - Arguments to find a DemoClass
   * @example
   * // Get one DemoClass
   * const demoClass = await prisma.demoClass.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DemoClassFindUniqueArgs>(args: Prisma.SelectSubset<T, DemoClassFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DemoClassClient<runtime.Types.Result.GetResult<Prisma.$DemoClassPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DemoClass that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DemoClassFindUniqueOrThrowArgs} args - Arguments to find a DemoClass
   * @example
   * // Get one DemoClass
   * const demoClass = await prisma.demoClass.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DemoClassFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DemoClassFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DemoClassClient<runtime.Types.Result.GetResult<Prisma.$DemoClassPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DemoClass that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DemoClassFindFirstArgs} args - Arguments to find a DemoClass
   * @example
   * // Get one DemoClass
   * const demoClass = await prisma.demoClass.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DemoClassFindFirstArgs>(args?: Prisma.SelectSubset<T, DemoClassFindFirstArgs<ExtArgs>>): Prisma.Prisma__DemoClassClient<runtime.Types.Result.GetResult<Prisma.$DemoClassPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DemoClass that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DemoClassFindFirstOrThrowArgs} args - Arguments to find a DemoClass
   * @example
   * // Get one DemoClass
   * const demoClass = await prisma.demoClass.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DemoClassFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DemoClassFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DemoClassClient<runtime.Types.Result.GetResult<Prisma.$DemoClassPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DemoClasses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DemoClassFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DemoClasses
   * const demoClasses = await prisma.demoClass.findMany()
   * 
   * // Get first 10 DemoClasses
   * const demoClasses = await prisma.demoClass.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const demoClassWithIdOnly = await prisma.demoClass.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DemoClassFindManyArgs>(args?: Prisma.SelectSubset<T, DemoClassFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DemoClassPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DemoClass.
   * @param {DemoClassCreateArgs} args - Arguments to create a DemoClass.
   * @example
   * // Create one DemoClass
   * const DemoClass = await prisma.demoClass.create({
   *   data: {
   *     // ... data to create a DemoClass
   *   }
   * })
   * 
   */
  create<T extends DemoClassCreateArgs>(args: Prisma.SelectSubset<T, DemoClassCreateArgs<ExtArgs>>): Prisma.Prisma__DemoClassClient<runtime.Types.Result.GetResult<Prisma.$DemoClassPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DemoClasses.
   * @param {DemoClassCreateManyArgs} args - Arguments to create many DemoClasses.
   * @example
   * // Create many DemoClasses
   * const demoClass = await prisma.demoClass.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DemoClassCreateManyArgs>(args?: Prisma.SelectSubset<T, DemoClassCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DemoClasses and returns the data saved in the database.
   * @param {DemoClassCreateManyAndReturnArgs} args - Arguments to create many DemoClasses.
   * @example
   * // Create many DemoClasses
   * const demoClass = await prisma.demoClass.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DemoClasses and only return the `id`
   * const demoClassWithIdOnly = await prisma.demoClass.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DemoClassCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DemoClassCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DemoClassPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DemoClass.
   * @param {DemoClassDeleteArgs} args - Arguments to delete one DemoClass.
   * @example
   * // Delete one DemoClass
   * const DemoClass = await prisma.demoClass.delete({
   *   where: {
   *     // ... filter to delete one DemoClass
   *   }
   * })
   * 
   */
  delete<T extends DemoClassDeleteArgs>(args: Prisma.SelectSubset<T, DemoClassDeleteArgs<ExtArgs>>): Prisma.Prisma__DemoClassClient<runtime.Types.Result.GetResult<Prisma.$DemoClassPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DemoClass.
   * @param {DemoClassUpdateArgs} args - Arguments to update one DemoClass.
   * @example
   * // Update one DemoClass
   * const demoClass = await prisma.demoClass.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DemoClassUpdateArgs>(args: Prisma.SelectSubset<T, DemoClassUpdateArgs<ExtArgs>>): Prisma.Prisma__DemoClassClient<runtime.Types.Result.GetResult<Prisma.$DemoClassPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DemoClasses.
   * @param {DemoClassDeleteManyArgs} args - Arguments to filter DemoClasses to delete.
   * @example
   * // Delete a few DemoClasses
   * const { count } = await prisma.demoClass.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DemoClassDeleteManyArgs>(args?: Prisma.SelectSubset<T, DemoClassDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DemoClasses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DemoClassUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DemoClasses
   * const demoClass = await prisma.demoClass.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DemoClassUpdateManyArgs>(args: Prisma.SelectSubset<T, DemoClassUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DemoClasses and returns the data updated in the database.
   * @param {DemoClassUpdateManyAndReturnArgs} args - Arguments to update many DemoClasses.
   * @example
   * // Update many DemoClasses
   * const demoClass = await prisma.demoClass.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DemoClasses and only return the `id`
   * const demoClassWithIdOnly = await prisma.demoClass.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DemoClassUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DemoClassUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DemoClassPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DemoClass.
   * @param {DemoClassUpsertArgs} args - Arguments to update or create a DemoClass.
   * @example
   * // Update or create a DemoClass
   * const demoClass = await prisma.demoClass.upsert({
   *   create: {
   *     // ... data to create a DemoClass
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DemoClass we want to update
   *   }
   * })
   */
  upsert<T extends DemoClassUpsertArgs>(args: Prisma.SelectSubset<T, DemoClassUpsertArgs<ExtArgs>>): Prisma.Prisma__DemoClassClient<runtime.Types.Result.GetResult<Prisma.$DemoClassPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DemoClasses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DemoClassCountArgs} args - Arguments to filter DemoClasses to count.
   * @example
   * // Count the number of DemoClasses
   * const count = await prisma.demoClass.count({
   *   where: {
   *     // ... the filter for the DemoClasses we want to count
   *   }
   * })
  **/
  count<T extends DemoClassCountArgs>(
    args?: Prisma.Subset<T, DemoClassCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DemoClassCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DemoClass.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DemoClassAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DemoClassAggregateArgs>(args: Prisma.Subset<T, DemoClassAggregateArgs>): Prisma.PrismaPromise<GetDemoClassAggregateType<T>>

  /**
   * Group by DemoClass.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DemoClassGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DemoClassGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DemoClassGroupByArgs['orderBy'] }
      : { orderBy?: DemoClassGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DemoClassGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDemoClassGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DemoClass model
 */
readonly fields: DemoClassFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DemoClass.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DemoClassClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  subject<T extends Prisma.SubjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SubjectDefaultArgs<ExtArgs>>): Prisma.Prisma__SubjectClient<runtime.Types.Result.GetResult<Prisma.$SubjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  batch<T extends Prisma.DemoClass$batchArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DemoClass$batchArgs<ExtArgs>>): Prisma.Prisma__BatchClient<runtime.Types.Result.GetResult<Prisma.$BatchPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DemoClass model
 */
export interface DemoClassFieldRefs {
  readonly id: Prisma.FieldRef<"DemoClass", 'String'>
  readonly title: Prisma.FieldRef<"DemoClass", 'String'>
  readonly videoURL: Prisma.FieldRef<"DemoClass", 'String'>
  readonly subjectId: Prisma.FieldRef<"DemoClass", 'String'>
  readonly batchId: Prisma.FieldRef<"DemoClass", 'String'>
  readonly userId: Prisma.FieldRef<"DemoClass", 'String'>
  readonly status: Prisma.FieldRef<"DemoClass", 'String'>
  readonly createdAt: Prisma.FieldRef<"DemoClass", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"DemoClass", 'DateTime'>
}
    

// Custom InputTypes
/**
 * DemoClass findUnique
 */
export type DemoClassFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DemoClass
   */
  select?: Prisma.DemoClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DemoClass
   */
  omit?: Prisma.DemoClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemoClassInclude<ExtArgs> | null
  /**
   * Filter, which DemoClass to fetch.
   */
  where: Prisma.DemoClassWhereUniqueInput
}

/**
 * DemoClass findUniqueOrThrow
 */
export type DemoClassFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DemoClass
   */
  select?: Prisma.DemoClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DemoClass
   */
  omit?: Prisma.DemoClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemoClassInclude<ExtArgs> | null
  /**
   * Filter, which DemoClass to fetch.
   */
  where: Prisma.DemoClassWhereUniqueInput
}

/**
 * DemoClass findFirst
 */
export type DemoClassFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DemoClass
   */
  select?: Prisma.DemoClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DemoClass
   */
  omit?: Prisma.DemoClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemoClassInclude<ExtArgs> | null
  /**
   * Filter, which DemoClass to fetch.
   */
  where?: Prisma.DemoClassWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DemoClasses to fetch.
   */
  orderBy?: Prisma.DemoClassOrderByWithRelationInput | Prisma.DemoClassOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DemoClasses.
   */
  cursor?: Prisma.DemoClassWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DemoClasses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DemoClasses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DemoClasses.
   */
  distinct?: Prisma.DemoClassScalarFieldEnum | Prisma.DemoClassScalarFieldEnum[]
}

/**
 * DemoClass findFirstOrThrow
 */
export type DemoClassFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DemoClass
   */
  select?: Prisma.DemoClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DemoClass
   */
  omit?: Prisma.DemoClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemoClassInclude<ExtArgs> | null
  /**
   * Filter, which DemoClass to fetch.
   */
  where?: Prisma.DemoClassWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DemoClasses to fetch.
   */
  orderBy?: Prisma.DemoClassOrderByWithRelationInput | Prisma.DemoClassOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DemoClasses.
   */
  cursor?: Prisma.DemoClassWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DemoClasses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DemoClasses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DemoClasses.
   */
  distinct?: Prisma.DemoClassScalarFieldEnum | Prisma.DemoClassScalarFieldEnum[]
}

/**
 * DemoClass findMany
 */
export type DemoClassFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DemoClass
   */
  select?: Prisma.DemoClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DemoClass
   */
  omit?: Prisma.DemoClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemoClassInclude<ExtArgs> | null
  /**
   * Filter, which DemoClasses to fetch.
   */
  where?: Prisma.DemoClassWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DemoClasses to fetch.
   */
  orderBy?: Prisma.DemoClassOrderByWithRelationInput | Prisma.DemoClassOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DemoClasses.
   */
  cursor?: Prisma.DemoClassWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DemoClasses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DemoClasses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DemoClasses.
   */
  distinct?: Prisma.DemoClassScalarFieldEnum | Prisma.DemoClassScalarFieldEnum[]
}

/**
 * DemoClass create
 */
export type DemoClassCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DemoClass
   */
  select?: Prisma.DemoClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DemoClass
   */
  omit?: Prisma.DemoClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemoClassInclude<ExtArgs> | null
  /**
   * The data needed to create a DemoClass.
   */
  data: Prisma.XOR<Prisma.DemoClassCreateInput, Prisma.DemoClassUncheckedCreateInput>
}

/**
 * DemoClass createMany
 */
export type DemoClassCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DemoClasses.
   */
  data: Prisma.DemoClassCreateManyInput | Prisma.DemoClassCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DemoClass createManyAndReturn
 */
export type DemoClassCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DemoClass
   */
  select?: Prisma.DemoClassSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DemoClass
   */
  omit?: Prisma.DemoClassOmit<ExtArgs> | null
  /**
   * The data used to create many DemoClasses.
   */
  data: Prisma.DemoClassCreateManyInput | Prisma.DemoClassCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemoClassIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DemoClass update
 */
export type DemoClassUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DemoClass
   */
  select?: Prisma.DemoClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DemoClass
   */
  omit?: Prisma.DemoClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemoClassInclude<ExtArgs> | null
  /**
   * The data needed to update a DemoClass.
   */
  data: Prisma.XOR<Prisma.DemoClassUpdateInput, Prisma.DemoClassUncheckedUpdateInput>
  /**
   * Choose, which DemoClass to update.
   */
  where: Prisma.DemoClassWhereUniqueInput
}

/**
 * DemoClass updateMany
 */
export type DemoClassUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DemoClasses.
   */
  data: Prisma.XOR<Prisma.DemoClassUpdateManyMutationInput, Prisma.DemoClassUncheckedUpdateManyInput>
  /**
   * Filter which DemoClasses to update
   */
  where?: Prisma.DemoClassWhereInput
  /**
   * Limit how many DemoClasses to update.
   */
  limit?: number
}

/**
 * DemoClass updateManyAndReturn
 */
export type DemoClassUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DemoClass
   */
  select?: Prisma.DemoClassSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DemoClass
   */
  omit?: Prisma.DemoClassOmit<ExtArgs> | null
  /**
   * The data used to update DemoClasses.
   */
  data: Prisma.XOR<Prisma.DemoClassUpdateManyMutationInput, Prisma.DemoClassUncheckedUpdateManyInput>
  /**
   * Filter which DemoClasses to update
   */
  where?: Prisma.DemoClassWhereInput
  /**
   * Limit how many DemoClasses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemoClassIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DemoClass upsert
 */
export type DemoClassUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DemoClass
   */
  select?: Prisma.DemoClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DemoClass
   */
  omit?: Prisma.DemoClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemoClassInclude<ExtArgs> | null
  /**
   * The filter to search for the DemoClass to update in case it exists.
   */
  where: Prisma.DemoClassWhereUniqueInput
  /**
   * In case the DemoClass found by the `where` argument doesn't exist, create a new DemoClass with this data.
   */
  create: Prisma.XOR<Prisma.DemoClassCreateInput, Prisma.DemoClassUncheckedCreateInput>
  /**
   * In case the DemoClass was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DemoClassUpdateInput, Prisma.DemoClassUncheckedUpdateInput>
}

/**
 * DemoClass delete
 */
export type DemoClassDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DemoClass
   */
  select?: Prisma.DemoClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DemoClass
   */
  omit?: Prisma.DemoClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemoClassInclude<ExtArgs> | null
  /**
   * Filter which DemoClass to delete.
   */
  where: Prisma.DemoClassWhereUniqueInput
}

/**
 * DemoClass deleteMany
 */
export type DemoClassDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DemoClasses to delete
   */
  where?: Prisma.DemoClassWhereInput
  /**
   * Limit how many DemoClasses to delete.
   */
  limit?: number
}

/**
 * DemoClass.batch
 */
export type DemoClass$batchArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Batch
   */
  select?: Prisma.BatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Batch
   */
  omit?: Prisma.BatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BatchInclude<ExtArgs> | null
  where?: Prisma.BatchWhereInput
}

/**
 * DemoClass without action
 */
export type DemoClassDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DemoClass
   */
  select?: Prisma.DemoClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DemoClass
   */
  omit?: Prisma.DemoClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DemoClassInclude<ExtArgs> | null
}
